### ISSUE TITLE
Upgrade Jobserver to support Spark 2.2.0

### ISSUE THREAD

**Issue by yuchaoran2011** [spark-jobserver/spark-jobserver#905] opened 2017-08-07 17:38 UTC
Spark 2.2.0 has been out for a while. We should make Jobserver support the latest and greatest Spark!

**Comment by leonsoft** [comment] 2017-08-09 08:09
and the docker files as well...

**Comment by hntd187** [comment] 2017-08-09 12:03
I don't _believe_ there is any reason we can't upgrade, but don't quote me on that one, Spark breaks things from version to version. Well, also, the fact they drop java7 and scala210 in 2.2.0 as well I believe.

**Comment by Majea** [comment] 2017-08-09 12:24
Is that the reason why spark-2.0-preview is still not merged into master? If yes, I'm a little worried because indeed Spark keeps evolving and it's probably hard to keep up the pace if they keep breaking things.

**Comment by hntd187** [comment] 2017-08-09 12:32
I believe we did merge it @Majea we just didn't remove the branch

**Comment by Majea** [comment] 2017-08-09 13:00
Sorry my bad, @marcoboi confirmed it.

**Comment by noorul** [comment] 2017-08-27 03:42
@yuchaoran2011 See #845

**Comment by noorul** [comment] 2017-10-10 05:12
Closing this as master supports 2.2.0

**Closed by noorul** 2017-10-10 05:12 UTC
Labels: enhancement

**Comment by hyitclj** [comment] 2017-10-25 07:59
why I don's use it ? detail in https://github.com/spark-jobserver/spark-jobserver/issues/936
