### ISSUE TITLE
Spark 3.0 support

### ISSUE THREAD

**Issue by ravi-unifi** [spark-jobserver/spark-jobserver#1315] opened 2020-07-09 17:45 UTC
Support spark 3.0 and scala 2.12.

**Comment by sivasai-quartic** [comment] 2020-07-15 18:30
Can we expect this anytime soon

**Comment by kjdoyle** [comment] 2020-08-24 19:43
Any news on support for Spark 3.0?

**Comment by valan4ik** [comment] 2020-10-23 06:54
Closing as duplicate of https://github.com/spark-jobserver/spark-jobserver/issues/1269

**Closed by valan4ik** 2020-10-23 06:54 UTC
Labels: feature request
