### ISSUE TITLE
Fail to run two jobs simultaneously in two contexts

### ISSUE THREAD

**Issue by ningjun** [spark-jobserver/spark-jobserver#147] opened 2015-05-08 14:46 UTC
I use spark-jobserver 0.4.1 with spark1.3.1  stand alone cluster. I precreate two contexts and then submit two jobs (each job to a different contexts) to the jobserver. It always failed with the following error. Note that I can run each job alone successfully.

Please advise

RN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, LAB4-WIN01.mycompany.com): java.io.IOException: org.apache.spark.SparkException: Failed to get broadcast_1_piece0 of broadcast_1
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1156)
	at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:164)
	at org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:64)
	at org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:64)
	at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:87)
	at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:58)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Failed to get broadcast_1_piece0 of broadcast_1
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1$$anonfun$2.apply(TorrentBroadcast.scala:137)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1$$anonfun$2.apply(TorrentBroadcast.scala:137)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply$mcVI$sp(TorrentBroadcast.scala:136)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply(TorrentBroadcast.scala:119)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply(TorrentBroadcast.scala:119)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.broadcast.TorrentBroadcast.org$apache$spark$broadcast$TorrentBroadcast$$readBlocks(TorrentBroadcast.scala:119)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:174)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1153)

**Comment by PierreVincent** [comment] 2015-05-12 17:09
Hi,

I'm seeing a similar error with Job Server 0.5.1 with Spark 1.3 (running in Standalone mode as well).

In my case I'm not creating custom contexts, contexts are created on the fly with the default options from the Job server configuration.

```
[2015-05-12 16:53:56,433] WARN  k.scheduler.TaskSetManager [] [] - Lost task 0.0 in stage 1.0 (TID 1, 192.168.173.14): java.io.IOException: org.apache.spark.SparkException: Failed to get broadcast_1_piece0 of broadcast_1
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1155)
	at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:164)
	at org.apache.spark.broadcast.TorrentBroadcast._value$lzycompute(TorrentBroadcast.scala:64)
	at org.apache.spark.broadcast.TorrentBroadcast._value(TorrentBroadcast.scala:64)
	at org.apache.spark.broadcast.TorrentBroadcast.getValue(TorrentBroadcast.scala:87)
	at org.apache.spark.broadcast.Broadcast.value(Broadcast.scala:70)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:61)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.spark.SparkException: Failed to get broadcast_1_piece0 of broadcast_1
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1$$anonfun$2.apply(TorrentBroadcast.scala:137)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1$$anonfun$2.apply(TorrentBroadcast.scala:137)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply$mcVI$sp(TorrentBroadcast.scala:136)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply(TorrentBroadcast.scala:119)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$org$apache$spark$broadcast$TorrentBroadcast$$readBlocks$1.apply(TorrentBroadcast.scala:119)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.broadcast.TorrentBroadcast.org$apache$spark$broadcast$TorrentBroadcast$$readBlocks(TorrentBroadcast.scala:119)
	at org.apache.spark.broadcast.TorrentBroadcast$$anonfun$readBroadcastBlock$1.apply(TorrentBroadcast.scala:174)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1152)
	... 12 more
```

I'm seeing a WARN a few seconds before the jobs fail, relating to multiple contexts running in the same JVM:

```
Multiple running SparkContexts detected in the same JVM!
org.apache.spark.SparkException: Only one SparkContext may be running in this JVM (see SPARK-2243). To ignore this error, set spark.driver.allowMultipleContexts = true. The currently running SparkContext was created at:
org.apache.spark.SparkContext.<init>(SparkContext.scala:80)
spark.jobserver.context.DefaultSparkContextFactory$$anon$1.<init>(SparkContextFactory.scala:41)
spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:41)
spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:34)
spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:261)
spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:104)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
	at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$1$$anonfun$apply$10.apply(SparkContext.scala:1811)
	at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$1$$anonfun$apply$10.apply(SparkContext.scala:1807)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$1.apply(SparkContext.scala:1807)
	at org.apache.spark.SparkContext$$anonfun$assertNoOtherContextIsRunning$1.apply(SparkContext.scala:1794)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.SparkContext$.assertNoOtherContextIsRunning(SparkContext.scala:1794)
	at org.apache.spark.SparkContext$.setActiveContext(SparkContext.scala:1846)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:1753)
	at spark.jobserver.context.DefaultSparkContextFactory$$anon$1.<init>(SparkContextFactory.scala:41)
	at spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:41)
	at spark.jobserver.context.DefaultSparkContextFactory.makeContext(SparkContextFactory.scala:34)
	at spark.jobserver.JobManagerActor.createContextFromConfig(JobManagerActor.scala:261)
	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:104)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
	at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
	at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Please let me know if there is any more info you need to investigate this, or if you'd like me to try out some options to debug!

Thanks,
Pierre

**Comment by velvia** [comment] 2015-05-12 21:49
Have you guys tried setting `spark.driver.allowMultipleContexts = true` ?

**Comment by PierreVincent** [comment] 2015-05-13 08:47
Hi velvia, thanks for the quick reply.

I am aware of this option being a workaround, but is that the recommended usage in Spark? Looking in at [SPARK-2243](https://issues.apache.org/jira/browse/SPARK-2243) it looks like they don't recommend using multiple contexts per JVM (which would explain why the option is set to false by default).

I will try this however to see if it works with the Job Server and if the apps are correctly running simultaneously.

**Comment by velvia** [comment] 2015-05-13 15:14
It's not recommended usage, but it's a workaround until we get the
JVM-per-context working.

On Wed, May 13, 2015 at 1:47 AM, Pierre Vincent <notifications@github.com>
wrote:

> Hi velvia, thanks for the quick reply.
>
> I am aware of this option being a workaround, but is that the recommended
> usage in Spark? Looking in at SPARK-2243
> <https://issues.apache.org/jira/browse/SPARK-2243> it looks like they
> don't recommend using multiple contexts per JVM (which would explain why
> the option is set to false by default).
>
> I will try this however to see if it works with the Job Server and if the
> apps are correctly running simultaneously.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/147#issuecomment-101577468>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by PierreVincent** [comment] 2015-05-14 16:18
Ok that makes sense. Do you have any indication as how much of a priority this is in the Job Server project? Is there anything that can be done to help?

**Comment by velvia** [comment] 2015-05-14 16:22
Pierre, I would say it's one of the higher priorities, but hopefully you
can understand I'm mostly maintaining this in my spare time.  Oh the ups
and downs of open source  :)

You can have a look at this PR:
https://github.com/spark-jobserver/spark-jobserver/pull/120
Try it out and see if it works for you.

On Thu, May 14, 2015 at 9:18 AM, Pierre Vincent <notifications@github.com>
wrote:

> Ok that makes sense. Do you have any indication as how much of a priority
> this is in the Job Server project? Is there anything that can be done to
> help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/147#issuecomment-102089715>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by PierreVincent** [comment] 2015-05-14 18:38
That's perfectly alright! I'm grateful for all the work put into this project and I would love to be of any help and contribute even though my skills in Akka are pretty limited!!

I will take a look at this PR to see if this working with my use case and I'll comment back.

Thanks.

**Comment by velvia** [comment] 2015-05-14 23:33
Awesome, thanks!

On Thu, May 14, 2015 at 11:38 AM, Pierre Vincent <notifications@github.com>
wrote:

> That's perfectly alright! I'm grateful for all the work put into this
> project and I would love to be of any help and contribute even though my
> skills in Akka are pretty limited!!
>
> I will take a look at this PR to see if this working with my use case and
> I'll comment back.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/147#issuecomment-102131092>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by PierreVincent** [comment] 2015-05-16 07:09
I have built the Job Server from the branch in that Pull Request and after making a couple of tweaks to the configuration and to some scripts, I was able to get it started and to run Spark Jobs.

It looks good so far, simultaneous jobs are running correctly now, so that's very promising!

I will comment directly on [#120](https://github.com/spark-jobserver/spark-jobserver/pull/120) about the issues I've had with the changes so hopefully that can make it to master in a reasonable amount of time.

**Comment by velvia** [comment] 2015-05-16 07:29
Awesome, thanks!

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by velvia** [comment] 2015-12-23 06:03
I think we can close this now, since the `feature/context-per-jvm` branch is pretty much done now.

**Closed by velvia** 2015-12-23 06:03 UTC
Labels: enhancement

**Comment by AnweshaSen** [comment] 2021-02-04 05:28
@PierreVincent can you please specify what is the cause of this error and what are the changes you have made to resolve this issue?? Since am getting similar error even with "spark.driver.allowMultipleContexts = true"

**Comment by valan4ik** [comment] 2021-02-04 08:30
@AnweshaSen did you also try setting `spark.jobserver.context-per-jvm = true`?
https://github.com/spark-jobserver/spark-jobserver/blob/master/README.md#context-per-jvm
https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/main/resources/application.conf#L20
