### ISSUE TITLE
SparkR and Pyspark support

### ISSUE THREAD

**Issue by rogersmarin** [spark-jobserver/spark-jobserver#406] opened 2016-03-16 23:37 UTC
Hi all,

We have a requirement to support both python and r jobs in addition to scala based spark jobs. We are currently looking at the livy server as an alternative to the spark job server given that it supports all 3 languages; however, given that our product is deeply integrated with the spark job server we are wondering if adding sparkr and pyspark support to the job server would be a better way to go.

Ideally we should be able to use the same apis in python and r that we use in scala based jobs including support for both shared contexts and named objects. 

I'm not entirely familiar with the spark job server internals so I'm wondering how much effort would be required to implement this feature.

Regards,
Roger

**Comment by velvia** [comment] 2016-03-17 06:48
See #196 .   Maybe these two issues can be merged.

**Comment by hntd187** [comment] 2016-06-03 23:22
As @velvia mentioned this is a duplicate of #196, so since there is discussion there, let's track that support there.

**Closed by hntd187** 2016-06-03 23:22 UTC
