### ISSUE TITLE
SparkJob remains in RUNNING state after unexpected SparkContext shutdown

### ISSUE THREAD

**Issue by zromi18** [spark-jobserver/spark-jobserver#856] opened 2017-06-06 15:30 UTC
I have noticed two related issues #757 and #109, but they do not cover a case when SparkContext is unexpectedly shutdown due to OutOfMemoryError on the driver or some other reasons not handled well. In such a case the already started SparkJobs remain in RUNNING state.

**Comment by zeoaman** [comment] 2017-06-08 09:45
I was testing SJS on EMR and realised that if server is restarted while a job is running, the job forever remains in RUNNING state. I do not think this case is covered either in any of the issues. I can probably provide steps to reproduce if it is an unexpected scenario.

**Comment by ruoguluo** [comment] 2017-08-23 02:40
I encountered the issue of the unexpected shutdown of context:

```
17921 [2017-08-22 17:35:09,695] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/hive-context] - stopped o.s.j.s.ServletContextHandler{/jobs/job,nu      ll}
17922 [2017-08-22 17:35:09,695] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/hive-context] - stopped o.s.j.s.ServletContextHandler{/jobs/json,n      ull}
17923 [2017-08-22 17:35:09,695] INFO  ver.handler.ContextHandler [] [akka://JobServer/user/context-supervisor/hive-context] - stopped o.s.j.s.ServletContextHandler{/jobs,null}
17924 [2017-08-22 17:35:09,748] INFO  rg.apache.spark.ui.SparkUI [] [akka://JobServer/user/context-supervisor/hive-context] - Stopped Spark web UI at http://10.24.100.165:52054
17925 [2017-08-22 17:35:09,770] ERROR .jobserver.JobManagerActor [] [akka://JobServer/user/context-supervisor/hive-context] - Got Throwable
17926 org.apache.spark.SparkException: Job 49 cancelled because SparkContext was shut down
```

**Comment by bsikander** [comment] 2019-05-21 13:09
Closing because the main issue was fixed by the referenced PR.

**Closed by bsikander** 2019-05-21 13:09 UTC
