### ISSUE TITLE
Spark Job Server not able to deal with custom exception

### ISSUE THREAD

**Issue by ishassan** [spark-jobserver/spark-jobserver#405] opened 2016-03-16 17:57 UTC
I'm running spark job server inside a docker container, and I've this spark job

```
package testpackage

import com.typesafe.config.Config
import org.apache.spark.SparkContext
import spark.jobserver._

object TestJob extends SparkJob {

  override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
          SparkJobValid
  }

  override def runJob(sc: SparkContext, config: Config): Any = {
    print("Start")

    try{
      throw new Exception("standard exception")
    }catch{
      case e: Exception => throw new Exception("standard exception")
    }

    print("End")
    1
  }
}
```

When I execute it with this curl request, it throws an exception as expected.
```
$ curl -d 't=1' 'localhost:8090/jobs?appName=spark_test&classPath=testpackage.TestJob&context=spark-context&sync=true&timeout=3600'

{
  "status": "ERROR",
  "result": {
    "message": "standard exception",
    "errorClass": "java.lang.Exception",
    "stack": ["testpackage.TestJob$.runJob(TestJob.scala:17)", "testpackage.TestJob$.runJob(TestJob.scala:8)", "spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:274)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)", "java.lang.Thread.run(Thread.java:745)"]
  }
}
```

The problem is that when I use a custom exception, as the following
```
package testpackage

import com.typesafe.config.Config
import org.apache.spark.SparkContext
import spark.jobserver._

class CustomException(msg: String) extends Exception(msg)
object TestJob extends SparkJob {

  override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
          SparkJobValid
  }

  override def runJob(sc: SparkContext, config: Config): Any = {
    print("Start")

    try{
      throw new CustomException("custom exception")
    }catch{
      case e: CustomException => throw new CustomException("custom exception")
    }

    print("End")
    1
  }
}
```

Executing this job doesn't produce the same error message. It shows me this instead
```
$ curl -d 't=1' 'localhost:8090/jobs?appName=spark_test&classPath=testpackage.TestJob&context=spark-context&sync=true&timeout=3600'
The server was not able to produce a timely response to your request.
```

and this is what I get on the server side
```
Start
==> /tmp/spark-job-server-log/jobserver-spark-context2469747457970586841/spark-job-server.log <==
[2016-03-11 14:28:52,763] WARN  .jobserver.JobManagerActor [] [akka://JobServer/user/jobManager-01-849d-38a877842070] - Exception from job 1842a76d-61e7-46f5-bdfb-dee1ff89a2a2: 
testpackage.CustomException: custom exception
    at testpackage.TestJob$.runJob(TestJob.scala:17)
    at testpackage.TestJob$.runJob(TestJob.scala:8)
    at spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:274)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

==> /tmp/spark-job-server-log/spark-job-server.log <==
[2016-03-11 14:28:52,790] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:40202/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A39527-0] - Association with remote system [akka.tcp://JobServer@127.0.0.1:39527] has failed, address is now gated for [5000] ms. Reason: [testpackage.CustomException] 

==> /tmp/spark-job-server-log/jobserver-spark-context2469747457970586841/spark-job-server.log <==
[2016-03-11 14:28:52,811] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:39527/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A40202-0] - Association with remote system [akka.tcp://JobServer@127.0.0.1:40202] has failed, address is now gated for [5000] ms. Reason: [Disassociated] 
[2016-03-11 14:28:56,971] WARN  .cluster.ClusterCoreDaemon [] [akka.tcp://JobServer@127.0.0.1:39527/system/cluster/core/daemon] - Cluster Node [akka.tcp://JobServer@127.0.0.1:39527] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://JobServer@127.0.0.1:40202, status = Up)]

==> /tmp/spark-job-server-log/spark-job-server.log <==
[2016-03-11 14:28:57,193] WARN  .cluster.ClusterCoreDaemon [] [akka.tcp://JobServer@127.0.0.1:40202/system/cluster/core/daemon] - Cluster Node [akka.tcp://JobServer@127.0.0.1:40202] - Marking node(s) as UNREACHABLE [Member(address = akka.tcp://JobServer@127.0.0.1:39527, status = Up)]
```

So, is it possible to use custom exceptions in spark job server?

**Comment by velvia** [comment] 2016-03-17 06:58
HI @ishassan , sorry right now there is a bug with the custom exception.

There is a workaround courtesy of Nick Xie, which is to not use the custom exception but capture the message and backtrace, something like this:

```java
public Object runJob(Object sparkContext, Config config) {
     ....
     } catch (Exception e) {
        throw initRuntimeException (e);
     }
  }
  protected static RuntimeException initRuntimeException(Throwable t) {
      final Throwable cause = getCause(t);
      final RuntimeException e = new RuntimeException(cause.getMessage());
      e.setStackTrace(cause.getStackTrace());
      return e;
  }

  protected static Throwable getCause(Throwable t) {
      Throwable cause = null; 
      Throwable result = t;

      while(null != (cause = result.getCause())  && (result != cause) ) {
          result = cause;
      }
      return result;   
  } 
```

For now we will probably wrap custom exceptions so they could be returned, because otherwise the Web/HTTP process would have to load all your custom application code.

**Comment by ishassan** [comment] 2016-03-17 11:40
Hi @velvia, thanks a lot for your reply!
So is this fixable any time soon? Do you know the cause of the problem or where it's stemming from?
I might want to have a look at it and give a patch if possible.

**Comment by velvia** [comment] 2016-03-17 16:35
It’s easy to fix.   In fact if I have time I can submit something in the next few days, basically based on Nick’s patch.

If you’d like to try though LMK.  Basically, in JobManagerActor.scala, you have this code:

     case Failure(error: Throwable) =>
        // If and only if job validation fails, JobErroredOut message is dropped silently in JobStatusActor.
        statusActor ! JobErroredOut(jobId, DateTime.now(), error)
        logger.warn("Exception from job " + jobId + ": ", error)


The idea is to intercept the error, wrap it as Nick’s code does in another RuntimeException (or maybe a SparkJobException), taking the stack trace and error message, and passing it on.    Should be pretty trivial.

As an added bonus, we can try filtering for custom exceptions, but not sure what is a good way to do that.

-Evan

**Comment by ishassan** [comment] 2016-03-18 15:05
Well, that'll work, but it's a workaround as you said, not a fix. It'll show up as a RuntimeException on the client side, eliminating the need to throw a custom exception in the first place.

So when I do this
```
case Failure(error: Throwable) =>
        // If and only if job validation fails, JobErroredOut message is dropped silently in JobStatusActor.

        // Wrapping the error inside a RuntimeException to handle the case of throwing custom exceptions.
        val wrappedError = wrapInRuntimeException(error)
        statusActor ! JobErroredOut(jobId, DateTime.now(), wrappedError)
        logger.warn("Exception from job " + jobId + ": ", error)

protected def wrapInRuntimeException(t: Throwable): RuntimeException = {
    val cause : Throwable = getRootCause(t)
    val e : RuntimeException = new RuntimeException(cause.getMessage())
    e.setStackTrace(cause.getStackTrace())
    return e
  }

  protected def getRootCause(t: Throwable): Throwable = {
    var result : Throwable = t
    var cause : Throwable = result.getCause()

    while(cause != null  && (result != cause) ) {
      result = cause
      cause = result.getCause()
    }
    return result
  }
```
 
This what shows up on client side
```
{
  "status": "ERROR",
  "result": {
    "message": "custom exception",
    "errorClass": "java.lang.RuntimeException",
    "stack": ["testpackage.TestJob$.runJob(TestJob.scala:18)", "testpackage.TestJob$.runJob(TestJob.scala:9)", "spark.jobserver.JobManagerActor$$anonfun$spark$jobserver$JobManagerActor$$getJobFuture$4.apply(JobManagerActor.scala:278)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)", "scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)", "java.lang.Thread.run(Thread.java:745)"]
  }
}
```
So if the error class shows up as a RuntimeException, why would I throw a CustomException in the first place, while I can throw RuntimeException with the custom message I want?

So is there a way to actually throw and show a custom exception? And do you know what the problem is that makes `statusActor` doesn't accept messages with custom exceptions?

And sure yes, I'd like to try :). I'm still a newbie and it'll be nice if I can contribute something.

**Comment by velvia** [comment] 2016-03-18 20:53
The problem is that StatusActor lives in the HTTP JVM, not in the forked process.   Thus the HTTP JVM does not have your custom exception class…  that’s the problem.   The solution would be to load the custom class into the HTTP JVM, but it pollutes that JVM and could potentially result in class conflicts (e.g. you might eventually have this problem, if you have lots of job jars, anyways).

The other solution would be to move the JobStatusActor into the forked process JVM.  I might actually do this, because there are some other advantages with doing so, related to HA and reliability.

**Comment by ishassan** [comment] 2016-03-19 17:37
Cool. Thanks a lot velvia for your help! In the meantime I made a commit out of this workaround until a better fix is available.

Cheers,

**Comment by velvia** [comment] 2016-03-20 22:32
No, problem, thanks for PR, I’ll have a look later.

**Comment by velvia** [comment] 2016-04-14 00:08
BTW, the PR has been merged to master, so at least the workaround exists for now.

**Closed** 2016-06-03 23:19 UTC
