### ISSUE TITLE
jobserver start_server.sh - java.lang.NoSuchMethodError: akka.actor.ActorRefFactory.dispatcher()Lscala/concurrent/ExecutionContextExecutor

### ISSUE THREAD

**Issue by marcob3t** [spark-jobserver/spark-jobserver#251] opened 2015-09-11 14:43 UTC
Hi all,

I deployed jobserver 0.5.3 using the "server_deploy.sh" script. When I tried to run the "server_start.sh" script on the remote server I found the following:

Exception in thread "main" java.lang.NoSuchMethodError: akka.actor.ActorRefFactory.dispatcher()Lscala/concurrent/ExecutionContextExecutor

I found the same issue on several posts and I have already tried the proposed suggestions, such as downgrading akka version to 2.2.4 or marking it both as "provided" and not. I have also tried to downgrade spray version to 1.2.3.

Here is my Dependencies.scala:

import sbt._

object Dependencies {
  val excludeCglib = ExclusionRule(organization = "org.sonatype.sisu.inject")
  val excludeJackson = ExclusionRule(organization = "org.codehaus.jackson")
  val excludeNettyIo = ExclusionRule(organization = "io.netty", artifact= "netty-all")
  val excludeAsm = ExclusionRule(organization = "asm")
  val excludeQQ = ExclusionRule(organization = "org.scalamacros")

  lazy val typeSafeConfigDeps = "com.typesafe" % "config" % "1.2.1"
  lazy val yammerDeps = "com.yammer.metrics" % "metrics-core" % "2.2.0"

  lazy val yodaDeps = Seq(
    "org.joda" % "joda-convert" % "1.2",
    "joda-time" % "joda-time" % "2.2"
  )

  lazy val akkaDeps = Seq(
    // Akka is provided because Spark already includes it, and Spark's version is shaded so it's not safe
    // to use this one
    "com.typesafe.akka" %% "akka-slf4j" % "2.2.4" % "provided",
    "io.spray" %% "spray-json" % "1.2.3" % "provided",
    "io.spray" %% "spray-can" % "1.2.3" % "provided",
    "io.spray" %% "spray-routing" % "1.2.3" % "provided",
    "io.spray" %% "spray-client" % "1.2.3" % "provided",
    yammerDeps
  ) ++ yodaDeps

  // val sparkVersion = sys.env.getOrElse("SPARK_VERSION", "1.3.1")
  val sparkVersion = "1.3.0"
  lazy val sparkDeps = Seq(
    "org.apache.spark" %% "spark-core" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ),
    // Force netty version.  This avoids some Spark netty dependency problem.
    "io.netty" % "netty-all" % "4.0.23.Final"
  )

  lazy val sparkExtraDeps = Seq(
    "org.apache.spark" %% "spark-sql" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ),
    "org.apache.spark" %% "spark-streaming" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ),
    "org.apache.spark" %% "spark-hive" % sparkVersion % "provided" excludeAll(excludeNettyIo, excludeQQ)
  )

  lazy val slickDeps = Seq(
    "com.typesafe.slick" %% "slick" % "2.1.0",
    "com.h2database" % "h2" % "1.3.170",
    "commons-dbcp" % "commons-dbcp" % "1.4"

  )

  lazy val logbackDeps = Seq(
    "ch.qos.logback" % "logback-classic" % "1.0.7"
  )

  lazy val coreTestDeps = Seq(
    "org.scalatest" %% "scalatest" % "2.2.1" % "test",
    "com.typesafe.akka" %% "akka-testkit" % "2.2.4" % "test",
    "io.spray" %% "spray-testkit" % "1.2.3" % "test"
  )

  lazy val serverDeps = apiDeps ++ yodaDeps
  lazy val apiDeps = sparkDeps :+ typeSafeConfigDeps

  val repos = Seq(
    "Snapshots-repo" at "http://scala-tools.org/repo-snapshots",
    "Typesafe Repo" at "http://repo.typesafe.com/typesafe/releases/",
    "Sonatype OSS Releases" at "http://oss.sonatype.org/content/repositories/releases/",
    "Sonatype snapshots" at "https://oss.sonatype.org/content/repositories/snapshots/",
    "Spray repo" at "http://repo.spray.io"
  )
}

Any help will be appreciated. Thanks.

**Comment by velvia** [comment] 2015-09-11 16:44
The key question will be what version or distribution of Spark you are using.  The error implies that the Spark distribution you have does not have a matching Akka or Scala version.   Changing the version in Dependencies.scala won’t affect your deploy, because the job server does not package Akka and Scala on purpose (as it would conflict with the Spark distribution anyways).

**Comment by bjoernlohrmann** [comment] 2015-09-18 13:18
@marcob3t In case you are using the Cloudera 5.4 distribution, the problem is indeed Cloudera's packaging of spark 1.3 with an older akka version. 

I have a workaround for this issue here, which seems to work but could use some more testing: https://github.com/bjoernlohrmann/spark-jobserver/tree/cdh-5.4

Currently, I am working for a CDH 5.3 fix as well.

**Comment by marcob3t** [comment] 2015-09-18 14:27
Yes, I am using Cloudera 5.4, so that is exactly the point I think; actually, I tested my spark-jobserver with Spark 1.4.1 (community edition) too and it works fine. So I will try your workaround.
Thank you all.

**Comment by velvia** [comment] 2015-09-18 17:02
One option we can have is to make the Akka version configurable via env variable.  But I’m not sure if that’s enough to get it to build.

**Comment by zeitos** [comment] 2015-09-22 16:18
should we close this one?

**Comment by marcob3t** [comment] 2015-10-02 07:22
Yes, thanks.

**Closed** 2015-10-07 02:50 UTC
Labels: wontfix

**Comment by lizanle521** [comment] 2016-11-29 07:56
i'm using jobserver-0.6.1-spark-1.5.2 and CDH-5.5.5 with spark-1.5.0. when i execute the script server_start.sh at the remote server. the problem also occured.
Exception in thread "main" java.lang.NoSuchMethodError: akka.actor.ActorRefFactory.dispatcher()Lscala/concurrent/ExecutionContextExecutor;

**Comment by lizanle521** [comment] 2016-11-29 12:58
![image](https://cloud.githubusercontent.com/assets/4190987/20710620/3a282694-b676-11e6-8a63-8a19060fc2ea.png)
it suffered me a lot . i have been working on this problem  for a day . could some please to tell me which version i should use or what change i should do to get rid of this .

**Comment by velvia** [comment] 2016-12-01 07:40
Sorry, but we would need more info to help you:

- Spark version and distro version
- Scala version
etc.

I suspect you are running an old build of Spark and CDH, look up the troubleshooting.md page and see if any of those tips help you.
