### ISSUE TITLE
Sorted maps return unsorted from REST response

### ISSUE THREAD

**Issue by jeffsteinmetz** [spark-jobserver/spark-jobserver#36] opened 2015-01-05 21:55 UTC
Simple example is a sorted word count.

In spark job:
```
val myTop = someRDD.takeOrdered(500)(WordCountOrdering)
myTop.toMap  // this is sorted but result from WebApi is re-mapped to any order
```

It also see the following ```resultToMap``` function isn't used:

https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/spark.jobserver/WebApi.scala#L364

If I have a moment I can look into it, but wanted to put it on the issues radar.
Need to dig into:  ```ctx.complete(resultToTable(result))```

https://github.com/spark-jobserver/spark-jobserver/blob/fc77c3c6ec90c9a79b721d3a9d0a2a0e78923808/job-server/src/spark.jobserver/WebApi.scala#L247

**Comment by velvia** [comment] 2015-03-26 07:33
Hi Jeff, do you still need this?

On Mon, Jan 5, 2015 at 1:55 PM, Jeff Steinmetz <notifications@github.com>
wrote:

> Simple example is a sorted word count.
>
> In spark job:
>
> val myTop = someRDD.takeOrdered(500)(WordCountOrdering)
> myTop.toMap  // this is sorted but result from WebApi is re-mapped to any order
>
> It also see the following resultToMap function isn't used:
>
>
> https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/src/spark.jobserver/WebApi.scala#L364
>
> If I have a moment I can look into it, but wanted to put it on the issues
> radar.
> Need to dig into: ctx.complete(resultToTable(result))
>
>
> https://github.com/spark-jobserver/spark-jobserver/blob/fc77c3c6ec90c9a79b721d3a9d0a2a0e78923808/job-server/src/spark.jobserver/WebApi.scala#L247
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/36>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by jeffsteinmetz** [comment] 2015-03-26 14:47
I am doing a good deal of direct exports to an S3 file (which retains 
sorting since it doesn’t pass back through the API), so in the interim it 
is a lower priority.

I will be using the direct API results eventually, so it will come back on 
the radar again soon enough.

jeff


From:  Evan Chan <notifications@github.com>
Reply-To:  spark-jobserver/spark-jobserver 
<reply+0053bdbb1956e88c4196b22a2fac5a626bc12b11e5fd07b392cf00000001112b7868
92a169ce032fa0de@reply.github.com>
Date:  Thursday, March 26, 2015 at 12:34 AM
To:  spark-jobserver/spark-jobserver <spark-jobserver@noreply.github.com>
Cc:  Jeff Steinmetz <jeffrey.steinmetz@gmail.com>
Subject:  Re: [spark-jobserver] Sorted maps return unsorted from REST 
response (#36)

Hi Jeff, do you still need this?

On Mon, Jan 5, 2015 at 1:55 PM, Jeff Steinmetz <notifications@github.com>
wrote:

> Simple example is a sorted word count.
>
> In spark job:
>
> val myTop = someRDD.takeOrdered(500)(WordCountOrdering)
> myTop.toMap  // this is sorted but result from WebApi is re-mapped to 
>any order
>
> It also see the following resultToMap function isn't used:
>
>
> 
>https://github.com/spark-jobserver/spark-jobserver/blob/master/job-server/
>src/spark.jobserver/WebApi.scala#L364
>
> If I have a moment I can look into it, but wanted to put it on the issues
> radar.
> Need to dig into: ctx.complete(resultToTable(result))
>
>
> 
>https://github.com/spark-jobserver/spark-jobserver/blob/fc77c3c6ec90c9a79b
>721d3a9d0a2a0e78923808/job-server/src/spark.jobserver/WebApi.scala#L247
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/36>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by alexpx** [comment] 2015-05-13 10:14
+1

**Comment by zeitos** [comment] 2015-11-25 00:07
Hey, are we sure toMap guarantees order?
```
scala> val p = sc.parallelize(Seq((3,4),(5,6),(7,8),(9,10), (1, 4)))
p: org.apache.spark.rdd.RDD[(Int, Int)] = ParallelCollectionRDD[14] at parallelize at <console>:24

scala> p.takeOrdered(10)(Ordering.by[(Int,Int),Int](_._1))
res32: Array[(Int, Int)] = Array((1,4), (3,4), (5,6), (7,8), (9,10))

scala> p.takeOrdered(10)(Ordering.by[(Int,Int),Int](_._1)).toMap
res33: scala.collection.immutable.Map[Int,Int] = Map(5 -> 6, 1 -> 4, 9 -> 10, 7 -> 8, 3 -> 4)
```

**Comment by velvia** [comment] 2015-11-25 07:59
Hmmm..... I think the problem is that if you return a scala `collection.Map` that is an inherently unsorted API.  We can try to preserve the ordering returned in the Map when we traverse it, but that is no guarantee given by Spark's APIs that that Map is ordered.  I think if we really want an ordered map, then instead it is better to return a `Seq` from the job, or maybe return a `SortedMap`.

**Comment by zeitos** [comment] 2015-11-25 15:43
@velvia ... I'm still new to scala but my understanding is that our map just wraps the other map with "result" key . So even if our map has no order it will not change the map returned by the job. 

The map returned by resultToTable will use (while serializing) the iteration order of the inner map. If the job returns a SortedMap  then resultToTable(sortedMap) will not deep copy the sortedMap and you should see the results in the expected order

**Comment by velvia** [comment] 2015-11-25 17:30
Yeah that is true.  We (in SJS) could preserve the order of the returned Map.   I’m just saying based on your experiment on the Spark shell, I’m not sure Spark itself guarantees any kind of order when you say “toMap”.

**Comment by zeitos** [comment] 2015-11-25 17:31
ohhhh, no... they don't and I think they shouldn't :D

**Comment by zeitos** [comment] 2016-04-13 22:30
I'm closing this issue since it's a spark feature. Feel free to reopen if you think so.

**Closed by zeitos** 2016-04-13 22:30 UTC
Labels: bug
