### ISSUE TITLE
Is there a limit on the job input size?

### ISSUE THREAD

**Issue by rmettu-rms** [spark-jobserver/spark-jobserver#659] opened 2016-11-18 16:30 UTC
Passing an input of 154K Bytes to the job running in sync mode with timeout of 100sec, results in this error - this is not from processing as I do not see a job being started in Spark Job Server UI  - 
```{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka.tcp://JobServer@127.0.0.1:39970/user/jobManager-40-871e-fb0dac87fbb3#-1461658055]] after [100000 ms]",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": [
      "akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)",
      "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)",
      "scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)",
      "scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)",
      "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)",
      "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)",
      "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)",
      "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)",
      "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)",
      "java.lang.Thread.run(Thread.java:745)"
    ]
  }
}```

**Comment by rmettu-rms** [comment] 2016-11-18 20:06
Looks like this is related to this option ```# Note that you can use this file to define settings not only for job server,
# but for your Spark jobs as well.  Spark job configuration merges with this configuration file as defaults.

akka {
  remote.netty.tcp {
    # This controls the maximum message size, including job results, that can be sent
    # maximum-frame-size = 10 MiB
  }
}```
Setting this config option didn't help, same error as before -- ```[2016-11-18 19:11:29,003] WARN  ReliableDeliverySupervisor [] [akka.tcp://JobServer@127.0.0.1:38514/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobServer%40127.0.0.1%3A58109-0] - Association with remote system [akka.tcp://JobServer@127.0.0.1:58109] has failed, address is now gated for [5000] ms. Reason: [Failed to write message to the transport] Caused by: [encoded string too long: 138398 bytes]
``` what else is needed?

**Comment by rmettu-rms** [comment] 2016-11-22 04:51
Here are the code changes that seem to address the issue - 
`caml111810:spark-jobserver rmettu$ git diff
diff --git a/job-server/src/spark.jobserver/JobManagerActor.scala b/job-server/src/spark.jobserver/JobManagerActor.scala
index f67afa6..4bec430 100644
--- a/job-server/src/spark.jobserver/JobManagerActor.scala
+++ b/job-server/src/spark.jobserver/JobManagerActor.scala
@@ -3,7 +3,7 @@ package spark.jobserver
 import java.util.concurrent.Executors._
 
 import akka.actor.{ActorRef, PoisonPill, Props}
-import com.typesafe.config.Config
+import com.typesafe.config.{Config, ConfigFactory}
 import java.net.{URI, URL}
 import java.util.concurrent.atomic.AtomicInteger
 
@@ -21,7 +21,7 @@ import spark.jobserver.util.{ContextURLClassLoader, SparkJobUtils}
 object JobManagerActor {
   // Messages
   case class Initialize(daoActor: ActorRef, resultActorOpt: Option[ActorRef])
-  case class StartJob(appName: String, classPath: String, config: Config,
+  case class StartJob(appName: String, classPath: String, configString: String,
                       subscribedEvents: Set[Class[_]])
   case class KillJob(jobId: String)
   case object GetContextConfig
@@ -131,7 +131,8 @@ class JobManagerActor(contextConfig: Config) extends InstrumentedActor {
           self ! PoisonPill
       }
 
-    case StartJob(appName, classPath, jobConfig, events) => {
+    case StartJob(appName, classPath, configString, events) => {
+      val jobConfig = ConfigFactory.parseString(configString)
       val loadedJars = jarLoader.getURLs
       getSideJars(jobConfig).foreach { jarUri =>
         val jarToLoad = new URL(convertJarUriSparkToJava(jarUri))
diff --git a/job-server/src/spark.jobserver/WebApi.scala b/job-server/src/spark.jobserver/WebApi.scala
index 7a44e3f..befee3f 100644
--- a/job-server/src/spark.jobserver/WebApi.scala
+++ b/job-server/src/spark.jobserver/WebApi.scala
@@ -482,7 +482,7 @@ class WebApi(system: ActorSystem,
                     val events = if (async) asyncEvents else syncEvents
                     val timeout = timeoutOpt.map(t => Timeout(t.seconds)).getOrElse(DefaultSyncTimeout)
                     val future = jobManager.get.ask(
-                      JobManagerActor.StartJob(appName, classPath, jobConfig, events))(timeout)
+                      JobManagerActor.StartJob(appName, classPath, jobConfig.root.render, events))(timeout)
                     respondWithMediaType(MediaTypes.`application/json`) { ctx =>
                       future.map {
                         case JobResult(_, res) =>`

@velvia please review the changes and let me know if you have any concerns /comments. I tried to submit a PR for this branch jobserver-0.6.2-spark-1.6.1 as we are using 0.6.2, got denied access. Please provide access or instructions on how to submit a PR.

**Comment by rmettu-rms** [comment] 2016-11-22 04:54
Comment on the changes : 
Passing in 155K job config input string resulted in Akka timeout response to the job. In WebApi, when creating JobManagerActor it fails to serialize jobConfig object when greater than 64K (not verified). Change is to serialize the config object as a string and recreate it when processing the job.

**Comment by velvia** [comment] 2016-11-22 07:45
Hi,

Ok, thanks for the patch.  So the issue is that the config is too big when serialized?   I think rather than just changing the type of message passed, I’d rather try a more efficient serialization of the original message - i.e. use Kryo, and also adjust the buffer size and transmission parameters upwards to accommodate that.

As for PR, doesn’t the standard fork - branch - submit pull request from Web API work?

**Comment by rmettu-rms** [comment] 2016-11-22 14:28
@velvia Thank you for your comments. I thought about Kryo but didn't find that Akka supports it by default, my understanding is it needs to be included from external implementations  http://doc.akka.io/docs/akka/2.4/scala/serialization.html#External_Akka_Serializers 
not knowing how robust and production ready these projects are, hence taking a safe approach by changing the type to string. If you know any of these implementations are production ready then I will be happy to contribute and test the changes, but for now as we are going to production soon appreciate a quick review of a PR which I will submit based on above changes.

**Comment by velvia** [comment] 2016-11-23 00:19
Are you not able to resolve the issue without code changes by increasing the Akka message size and buffer size?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by rmettu-rms** [comment] 2016-11-23 00:22
No, it didn’t work. I am looking into Kryo serialization (https://github.com/romix/akka-kryo-serialization)  but running into issue starting the job server.

**Comment by velvia** [comment] 2016-11-23 00:27
Sorry which settings did you try again?

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by rmettu-rms** [comment] 2016-11-23 00:28
akka {
  loglevel = "DEBUG"
  log-config-on-start = on
  actor.debug {
    receive = on
    autoreceive = on
  }
  remote {
    maximum-payload-bytes = 20 MiB
    log-received-messages = on
    log-sent-messages = on
    log-frame-size-exceeding = 1000b
  }
  remote.netty.tcp {
    message-frame-size =  10 MiB
    send-buffer-size = 20 MiB
    receive-buffer-size = 20 MiB
    maximum-frame-size = 10 MiB
  }
}

**Comment by rmettu-rms** [comment] 2016-11-23 02:55
@velvia wondering if you canhelp  review these changes that I made to use Kryo serializer - issue is Spark JobServer is not starting up properly - Added these changes in application.conf ```akka {
  # Use SLF4J/logback for deployed environment logging
  loggers = ["akka.event.slf4j.Slf4jLogger"]

  extensions = ["com.romix.akka.serialization.kryo.KryoSerializationExtension$"]

  actor {
    serialize-messages = on

    kryo  {
      # Possibles values for type are: graph or nograph
      # graph supports serialization of object graphs with shared nodes
      # and cyclic references, but this comes at the expense of a small
      # overhead nograph does not support object grpahs with shared nodes,
      # but is usually faster
      type = "graph"

      # Possible values for idstrategy are:
      # default, explicit, incremental, automatic
      #
      # default - slowest and produces bigger serialized representation.
      # Contains fully-qualified class names (FQCNs) for each class. Note
      # that selecting this strategy does not work in version 0.3.2, but
      # is available from 0.3.3 onward.
      #
      # explicit - fast and produces compact serialized representation.
      # Requires that all classes that will be serialized are pre-registered
      # using the "mappings" and "classes" sections. To guarantee that both
      # sender and receiver use the same numeric ids for the same classes it
      # is advised to provide exactly the same entries in the "mappings"
      # section.
      #
      # incremental - fast and produces compact serialized representation.
      # Support optional pre-registering of classes using the "mappings"
      # and "classes" sections. If class is not pre-registered, it will be
      # registered dynamically by picking a next available id To guarantee
      # that both sender and receiver use the same numeric ids for the same
      # classes it is advised to pre-register them using at least the "classes" section.
      #
      # automatic -  use the pre-registered classes with fallback to FQCNs
      # Contains fully-qualified class names (FQCNs) for each non pre-registered
      # class in the "mappings" and "classes" sections. This strategy was
      # added in version 0.4.1 and will not work with the previous versions

      idstrategy = "incremental"

      # Define a default queue builder, by default ConcurrentLinkedQueue is used.
      # Create your own queue builder by implementing the trait QueueBuilder,
      # useful for paranoid GC users that want to use JCtools MpmcArrayQueue for example.
      #
      # If you pass a bounded queue make sure its capacity is equal or greater than the
      # maximum concurrent remote dispatcher threads your application will ever have
      # running; failing to do this will have a negative performance impact:
      #
      # custom-queue-builder = "a.b.c.KryoQueueBuilder"

      # Define a default size for byte buffers used during serialization
      buffer-size = 4096

      # The serialization byte buffers are doubled as needed until they
      # exceed max-buffer-size and an exception is thrown. Can be -1
      # for no maximum.
      max-buffer-size = -1

      # If set, akka uses manifests to put a class name
      # of the top-level object into each message
      use-manifests = false

      # If set it will use the UnsafeInput and UnsafeOutput
      # Kyro IO instances. Please note that there is no guarantee
      # for backward/forward compatibility of unsafe serialization.
      # It is also not compatible with the safe-serialized values.
      # The unsafe IO usually creates bugger payloads but is faster
      # for some types, e.g. native arrays.
      use-unsafe = false

      # The transformations that have be done while serialization
      # Supported transformations: compression and encryption
      # accepted values(comma separated if multiple): off | lz4 | deflate | aes
      # Transformations occur in the order they are specified
      post-serialization-transformations = "lz4"

      # Settings for aes encryption, if included in transformations AES
      # algo mode, key and custom key class can be specified AES algo mode
      # defaults to 'AES/CBC/PKCS5Padding' and key to 'ThisIsASecretKey'.
      # If custom key class is provided, Kryo will use the class specified
      # by a fully qualified class name to get custom AES key. Such a
      # class should define the method 'kryoAESKey'. This key overrides 'key'.
      # If class doesn't contain 'kryoAESKey' method, specified key is used.
      # If this is not present, default key is used
      # encryption {
      #  aes {
      #    mode = "AES/CBC/PKCS5Padding"
      #    key = j68KkRjq21ykRGAQ
      #    IV-length = 16
      #    custom-key-class = "CustomAESKeyClass"
      #  }
      #}

      # Log implicitly registered classes. Useful, if you want to know all
      # classes which are serialized. You can then use this information in
      # the mappings and/or classes sections
      implicit-registration-logging = false

      # If enabled, Kryo logs a lot of information about serialization process.
      # Useful for debugging and lowl-level tweaking
      kryo-trace = false

      # If proviced, Kryo uses the class specified by a fully qualified
      # class name to perform a custom initialization of Kryo instances in
      # addition to what is done automatically based on the config file.
      # kryo-custom-serializer-init = "CustomKryoSerializerInitFQCN"

      # If enabled, allows Kryo to resolve subclasses of registered Types.
      #
      # This is primarily useful when idstrategy is set to "explicit". In this
      # case, all classes to be serialized must be explicitly registered. The
      # problem is that a large number of common Scala and Akka types (such as
      # Map and ActorRef) are actually traits that mask a large number of
      # specialized classes that deal with various situations and optimizations.
      # It isn't straightforward to register all of these, so you can instead
      # register a single supertype, with a serializer that can handle *all* of
      # the subclasses, and the subclasses get serialized with that.
      #
      # Use this with care: you should only rely on this when you are confident
      # that the superclass serializer covers all of the special cases properly.
      resolve-subclasses = false

      # Define mappings from a fully qualified class name to a numeric id.
      # Smaller ids lead to smaller sizes of serialized representations.
      #
      # This section is:
      # - mandatory for idstrategy="explicit"
      # - ignored   for idstrategy="default"
      # - optional  for incremental and automatic
      #
      # The smallest possible id should start at 20 (or even higher), because
      # ids below it are used by Kryo internally e.g. for built-in Java and
      # Scala types
      mappings {
        "com.typesafe.config.Config" = 200
      #  "package1.name1.className1" = 20,
      #  "package2.name2.className2" = 21
      }

      # Define a set of fully qualified class names for
      # classes to be used for serialization.
      # The ids for those classes will be assigned automatically,
      # but respecting the order of declaration in this section
      #
      # This section is ignored for idstrategy="default" and optional for
      # all other.
      #classes = [
      #  "package3.name3.className3",
      #  "package4.name4.className4"
      #]
    }
    provider = "akka.cluster.ClusterActorRefProvider"
    warn-about-java-serializer-usage = off
    serializers {
      java = "akka.serialization.JavaSerializer"
      # Define kryo serializer
      kryo = "com.romix.akka.serialization.kryo.KryoSerializer"
    }

    serialization-bindings {
      "com.typesafe.config.Config" = kryo
    }
  }

  remote {
    log-remote-lifecycle-events = off
    netty.tcp {
      hostname = "127.0.0.1"
      port = 0
      send-buffer-size = 20 MiB
      receive-buffer-size = 20 MiB
      # This controls the maximum message size, including job results, that can be sent
      maximum-frame-size = 10 MiB
    }
  }

  cluster {
    auto-down-unreachable-after = 20s
    metrics.enabled = off
    failure-detector.acceptable-heartbeat-pause = 3s
    failure-detector.threshold = 12.0
  }
}```

In Dependencies file added - 
```
lazy val akkaDeps = Seq(
    // Akka is provided because Spark already includes it, and Spark's version is shaded so it's not safe
    // to use this one
    "com.typesafe.akka" %% "akka-slf4j" % akka % "provided",
    "com.typesafe.akka" %% "akka-cluster" % akka exclude("com.typesafe.akka", "akka-remote"),
    "com.github.romix.akka" %% "akka-kryo-serialization" % "0.3.3",
    "io.spray" %% "spray-json" % sprayJson,
    "io.spray" %% "spray-can" % spray,
    "io.spray" %% "spray-caching" % spray,
    "io.spray" %% "spray-routing" % spray,
    "io.spray" %% "spray-client" % spray,
    yammerDeps
  )
```

Last few messages in the spark-job-server.log 
```
    464 
    465 [2016-11-22 15:53:33,796] INFO  ka.event.slf4j.Slf4jLogger [] [] - Slf4jLogger started
    466 [2016-11-22 15:53:33,805] DEBUG akka.event.EventStream [] [EventStream(akka://JobServer)] - logger log1-Slf4jLogger started
    467 [2016-11-22 15:53:33,809] DEBUG akka.event.EventStream [] [EventStream(akka://JobServer)] - Default Loggers started
    468 [2016-11-22 15:53:33,865] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got mappings: Map(com.typesafe.config.Config -> 200)
    469 [2016-11-22 15:53:33,866] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got classnames for incremental strategy: []
    470 [2016-11-22 15:53:33,866] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got buffer-size: 4096
    471 [2016-11-22 15:53:33,866] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got max-buffer-size: -1
    472 [2016-11-22 15:53:33,866] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got id strategy: incremental
    473 [2016-11-22 15:53:33,867] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got serializer type: graph
    474 [2016-11-22 15:53:33,867] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got implicit registration logging: false
    475 [2016-11-22 15:53:33,867] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got use manifests: false
    476 [2016-11-22 15:53:33,867] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got custom serializer init class: null
    477 [2016-11-22 15:53:33,867] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got serializer init class: null
    478 [2016-11-22 15:53:33,869] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got customizer instance: Failure(java.lang.NullPointerException)
    479 [2016-11-22 15:53:33,871] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got customizer method: Failure(java.lang.NullPointerException)
    480 [2016-11-22 15:53:33,871] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got custom aes key class: null
    481 [2016-11-22 15:53:33,872] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got custom key class: null
    482 [2016-11-22 15:53:33,873] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got custom aes key instance: Failure(java.lang.NullPointerException)
    483 [2016-11-22 15:53:33,874] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got custom aes key method: Failure(java.lang.NullPointerException)
    484 [2016-11-22 15:53:33,879] DEBUG rializer(akka://JobServer) [] [com.romix.akka.serialization.kryo.KryoSerializer(akka://JobServer)] - Got transformations: lz4
```

**Comment by velvia** [comment] 2016-11-23 05:11
I looked over the config changes and they look fine.  Don’t see anything unusual.  I also don’t see any SJS-specific errors though… can you provide details of how it is not starting up properly?

My hesitation over changing the case class definition is that that makes the rest of the stack not as type safe.  I know one can define a custom Akka  serializer which is not that hard, I just did it for my other project.   If Kryo is not working I would try that if you have time.

**Comment by rmettu-rms** [comment] 2016-11-28 20:50
@velvia please review the latest changes in PR https://github.com/spark-jobserver/spark-jobserver/pull/661. As suggested instead of changing the type for Config object, implemented Akka serialization extension for StartJob message.

**Comment by noorul** [comment] 2017-01-29 01:50
PR is merged. Closing this.

**Closed by noorul** 2017-01-29 01:50 UTC
