### ISSUE TITLE
DELETE /binaries not working

### ISSUE THREAD

**Issue by james-q-arnold** [spark-jobserver/spark-jobserver#896] opened 2017-07-18 16:45 UTC
The web API call 'DELETE /binaries/<appname>' appears not to work.  We are using 0.7 with a generic configuration (configured for our local environment, nothing "unusual").  After a successful POST to upload the binary, the DELETE gives the following response:

```
{
  "status": "ERROR",
  "result": {
    "message": "Failure(slick.SlickException: Failed to delete binary: sjsSearch from database) (of class scala.util.Failure)",
    "errorClass": "scala.MatchError",
    "stack": ["spark.jobserver.WebApi$$anonfun$binaryRoutes$1$$anonfun$apply$22$$anonfun$apply$23$$anonfun$apply$24.apply(WebApi.scala:265)", "spark.jobserver.WebApi$$anonfun$binaryRoutes$1$$anonfun$apply$22$$anonfun$apply$23$$anonfun$apply$24.apply(WebApi.scala:265)", "scala.util.Success$$anonfun$map$1.apply(Try.scala:206)", "scala.util.Try$.apply(Try.scala:161)", "scala.util.Success.map(Try.scala:206)", "scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)", "scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)", "scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)", "akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)", "akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)", "akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)", "akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)", "scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)", "akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)", "akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"]
  }
}
```

This has several consequences:

- As we upload new binaries (jar files), the files accumulate in the upload directory.
- The H2 database appears to hold a copy of the uploaded binaries, so the H2 database grows.
-  The DELETE call neither removes the jar file nor shrinks the H2 database.

**Comment by thoHeinze** [comment] 2017-07-21 13:57
This is a duplicate of the issue https://github.com/spark-jobserver/spark-jobserver/issues/824. Please use the current master, the problem was already solved there: https://github.com/spark-jobserver/spark-jobserver/pull/834

Regarding the upload folder, currently SJS will save a cached copy inside this folder even your DB is running on the same hosts. We are working on making this optional see https://github.com/spark-jobserver/spark-jobserver/issues/876

**Comment by noorul** [comment] 2017-08-06 02:22
Closing this! Please use master

**Closed by noorul** 2017-08-06 02:22 UTC
