### ISSUE TITLE
Failed to start jobserver again if stop it while jobs are running.

### ISSUE THREAD

**Issue by lionelfeng** [spark-jobserver/spark-jobserver#445] opened 2016-04-28 16:40 UTC
Current workaround is to delete the data file before restarting it.

log:
```shell
[2016-04-28 08:47:48,867] INFO  rk.jobserver.io.JobFileDAO [] [] - rootDir is /tmp/spark-job-server/filedao/data
[2016-04-28 08:47:49,261] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:86)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:58)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:542)
    at spark.jobserver.JobServer$.start(JobServer.scala:59)
    at spark.jobserver.JobServer$.main(JobServer.scala:121)
    at spark.jobserver.JobServer.main(JobServer.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:56)
    at java.lang.reflect.Method.invoke(Method.java:620)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.typesafe.config.ConfigException$Parse: String: 1: Key '"1a3c330b-5ee9-4497-a0b9-caa6ad170549"' may not be followed by token: end of file (if you intended '"1a3c330b-5ee9-4497-a0b9-caa6ad170549"' to be part of a value, instead of a key, try adding double quotes around the whole value)
    at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435)
    at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431)
    at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:786)
    at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
    at com.typesafe.config.impl.Parser.parse(Parser.java:34)
    at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
    at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210)
    at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
    at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
    at com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
    at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:823)
    at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:827)
    at spark.jobserver.io.JobFileDAO.readJobConfig(JobFileDAO.scala:190)
    at spark.jobserver.io.JobFileDAO.init(JobFileDAO.scala:78)
    at spark.jobse
```

**Comment by velvia** [comment] 2016-04-28 20:20
I suggest we get rid of the FileDAO and support H2 as a default.  It was never meant to be a robust solution.

**Comment by barrybecker4** [comment] 2016-06-13 14:33
I just hit this exact problem, but I do not understand the suggested workaround. What datafile should I delete?

**Comment by barrybecker4** [comment] 2016-06-13 14:34
Here is the error from my log:
$ cat spark-job-server.log
[2016-06-13 07:30:25,459] ERROR spark.jobserver.JobServer$ [] [] - Unable to start Spark JobServer:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at spark.jobserver.JobServer$.start(JobServer.scala:58)
        at spark.jobserver.JobServer$.main(JobServer.scala:130)
        at spark.jobserver.JobServer.main(JobServer.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.typesafe.config.ConfigException$Parse: String: 1: Key 'f7a41d9c-42ea-48e7-ac74-631a3d9bfc80' may not be followed by token: end of file (if you intended 'f7a41d9c-42ea-48e7-ac74-631a3d9bfc80' to be part of a value, instead of a key, try adding double quotes around the whole value)
        at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435)
        at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431)
        at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:786)
        at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
        at com.typesafe.config.impl.Parser.parse(Parser.java:34)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:210)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
        at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:823)
        at com.typesafe.config.ConfigFactory.parseString(ConfigFactory.java:827)
        at spark.jobserver.io.JobFileDAO.readJobConfig(JobFileDAO.scala:190)
        at spark.jobserver.io.JobFileDAO.init(JobFileDAO.scala:78)
        at spark.jobserver.io.JobFileDAO.<init>(JobFileDAO.scala:30)
        ... 16 more

**Comment by lionelfeng** [comment] 2016-06-13 14:35
@barrybecker4 

``rm /tmp/spark-job-server/filedao/data/configs.data
rm /tmp/spark-job-server/filedao/data/jobs.data```

**Comment by barrybecker4** [comment] 2016-06-13 14:39
Thanks for the quick response. That worked.
I should mention that I am running on windows so the path was actually C:/tmp/spark/job-server/filedao/data

**Comment by noorul** [comment] 2016-06-14 22:54
I think file dao should be used for simple testing. Since now you have work around, I am closing this.

**Closed by noorul** 2016-06-14 22:54 UTC
