### ISSUE TITLE
[Mesos cluster mode] Context creation fails when sufficient resources are not available for driver but context is getting created eventually when resource are available.

### ISSUE THREAD

**Issue by vatsalmevada** [spark-jobserver/spark-jobserver#874] opened 2017-06-23 10:34 UTC
I have configured job-server for Mesos cluster mode. 

When sufficient resources are not available in the cluster for my driver program, the context creation request fails because of context creation timeout. However, the driver remains in the queued state on mesos dispatcher and it gets started whenever resources are available in the cluster. It also creates the spark context on the cluster. 

There is no possible way to distinguish whether driver program is queued up or the context creation actually failed. This makes it almost impossible to monitor the queued driver program and/or kill the driver program to avoid delayed the creation of the spark context.

**Comment by zromi18** [comment] 2017-07-13 12:33
I think that creating SparkContext should be asynchronous. I am already working on the additions semantics to the contexts REST API resources keeping original behavior for the backward compatibility reasons.

The request to create SparkContext should allow asynchronous mode:
`POST /contexts/[context-name]?sync=false
ReplyTo: [callback-url]`

should respond with:
`HTTP/1.1 202 Accepted
Location: /contexts-queue/[context-name]`

then the request to:
`GET /contexts-queue/[context-name]`

should respond with if the SparkContext is still being created:
`HTTP/1.1 200 OK
{
  "status": "PENDING",
  "eta": "60000"
}`
or with this, if the SparkContext has been already created:
'HTTP/1.1 303 See Other
Location: /contexts/[context-name]'

apart from that once the SparkContext is created and ReplyTo HTTP Header has been provided in the first request the below request should be made by Spark JobServer:
`POST [callback-url]
{
  "status": "SUCCESS",
  "result": "Context initialized",
  "context": [context-name]
}`

**Comment by velvia** [comment] 2017-07-13 17:43
Hi Roman,

Thanks, this makes sense to me.  Then we can avoid the timeouts that are associated with this.

-Evan

**Comment by vatsalmevada** [comment] 2017-11-24 11:22
@zromi18 Are the changes suggested by you already available in master by any chance?

**Comment by zromi18** [comment] 2017-11-25 10:41
@vatsalmevada sorry, not yet. I have them locally and I am struggling with the merge to the up-stream. I need a couple more days.

**Comment by vatsalmevada** [comment] 2017-11-27 10:26
@zromi18 From the approach mentioned by you in earlier comment, I understand that the context creation will be asynchronous. Do you think this change can fix [this](https://github.com/spark-jobserver/spark-jobserver/issues/743) issue too? The behavior is similar to this one but with stand alone cluster.

**Comment by vatsalmevada** [comment] 2017-12-27 08:07
@zromi18 are the changes already committed in up-stream by any chance?

**Comment by bsikander** [comment] 2019-05-21 13:04
The problem is fixed in the latest release of jobserver. The queued contexts are deleted automatically by jobserver as soon as they try to connect back. Jobserver also return 503 Not enough resources back as a response to users.

**Closed by bsikander** 2019-05-21 13:04 UTC
