### ISSUE TITLE
Question: What needs to be done to have job-server support spark 1.6.2 and 2.0?

### ISSUE THREAD

**Issue by barrybecker4** [spark-jobserver/spark-jobserver#543] opened 2016-07-11 16:28 UTC
We currently use spark 1.6.0 with job-server 0.6.2.
We would like to use job-server with spark 1.6.2 (or even better spark 2.0.) because there are some known issues in the spark version we are using that are (hopefully) fixed in later releases.
Is anyone currently working on making job-server work with 0.6.2? What needs to be done to have that happen? Are there known problems with running job-server with spark 0.6.2? 

I suspect that getting job-server to work with spark 2.0 will require significantly more work. I looked at the network view, but do not see a branch for the effort to upgrade job-server to work with spark 2.0.x. I might be able to contribute, but it would be helpful to collaborate with someone else who already knows job-server development.

**Comment by velvia** [comment] 2016-07-11 17:05
Hi Barry,

All you should need to do to get Spark 1.6.2 is to set SPARK_VERSION to that before compiling.  

Spark 2.0 we have not scoped out the effort yet.  

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by hntd187** [comment] 2016-07-11 21:18
Hey Barry,

Since 1.6.2 is a minor version it's compatible with all the other versions in the 1.6.x branch, you should be able to compile against it no problems.

Now for Spark 2.0, there are a number of things that make Spark 2.0 a tricky animal to understand at this point, not all of it bad though. I've been playing with it and using it internally for a bit (not in SJS) but we will have to do a good bit of work in the context creation and management. As well, it's my understanding Spark is going to no longer be using Akka, which should give us a lot of new freedom, we've been kind of limited in what we're capable of by having to make Spark's akka version for some time, but if we are free from that requirement we can finally upgrade Akka (if we choose) but Akka 2.4.x is Scala 2.11 and Java7/8 only and they are different enough from 2.3.x to 2.4.x to make it harder than flipping a switch, but there are some serious performance considerations from one to the other. Mostly because 2.4.x uses java.util.nio while 2.3.x maintains Java6 support, so no NIO in it. I think since most people won't be jumping to Spark 2.0 right away we'll have some time to react, but me personally, I'm trying to finish my other responsibilities so I can tackle the 2.0 update asap.

**Comment by jacek-lewandowski** [comment] 2016-07-12 15:18
IMHO this is good time to remove Akka as a dependency of API. This should be pretty easy because the only class used from Akka there is `Timeout`. We should replace it with `scala.concurrent.FiniteDuration` because it doesn't force people to add additional dependencies to the project.

**Comment by velvia** [comment] 2016-07-12 16:49
Yes, I’m in favor of removing Akka from the API if that’s the only dependency.

**Comment by TianLangStudio** [comment] 2016-08-02 13:17
@hntd187 Why remove Akka as a dependency on Spark2.0 ? What are the causes?

**Comment by hntd187** [comment] 2016-08-02 14:39
@TianLangStudio Spark is removing it as a dependency. We would want to remove akka from our api dependency since it bloats the dependency when we only use it for timeouts. We will still keep it in the main job server, we are talking about removing it only from the api module.

**Comment by TianLangStudio** [comment] 2016-08-03 01:54
@hntd187  Thanks, I am a beginner in Akka, I think it make easy to write concurrent program.  I thought was there some wrong with Akka,When i see spark2.0 remove it from dependency. Thanks again

**Comment by barrybecker4** [comment] 2016-10-24 20:32
@hntd187 and others, is there a current effort to have a release of jobserver that supports 2.x? I just upgraded our own code to use spark 2.0.1, but we really cannot move to spark 2.0.1 until there is a jobserver release that supports it. I would be happy to help with testing if anyone has something working in a branch.

**Comment by f1yegor** [comment] 2016-10-24 21:16
could you look here https://github.com/f1yegor/spark-jobserver/commits/spark-2.0-preview ?

**Comment by barrybecker4** [comment] 2016-11-06 13:28
I think this issue could be duped to #570. I will try out the preview branch soon (will need to update it to use 2.0.1 though).

**Comment by barrybecker4** [comment] 2016-11-07 02:16
I got the branch building, but when I tried to get rid of the warnings by using Spark Session instead of SqlContext, HiveContext, or StreamingContext, I got lost. Is the ContextLike trait still needed? I tried to keep it, but ran into problems. StreamingContext is supposed to eventually be encompassed by SessionContext, but isnt yet. My work is in https://github.com/barrybecker4/spark-jobserver/tree/spark-2.0.1-bb

**Comment by barrybecker4** [comment] 2016-12-15 19:03
@velvia 
I am running a version of jobserver based on the 2.0-preview with spark-2.0.2 and scala-2.11.6. 
Has anything changed in the way that a SQLContext is uploaded to the jobserver?
When I do
 curl -d "" localhost:8090/contexts/sql-context?context-factory=spark.jobserver.context.SQLContextFactory
I get this error:
`{
  "status": "CONTEXT INIT ERROR",
  "result": {
    "errorClass": "java.lang.IllegalArgumentException",
    "cause": "namenode",
    "stack": ["org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:374)", "org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)", "org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)", "org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:668)", "org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:604)", "org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:148)", "org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2598)", "org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:91)", "org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2632)", "org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2614)", "org.apache.hadoop.fs.FileSystem.get(FileSystem.java:370)", "org.apache.spark.util.Utils$.getHadoopFileSystem(Utils.scala:1822)", "org.apache.spark.scheduler.EventLoggingListener.<init>(EventLoggingListener.scala:67)", "org.apache.spark.SparkContext.<init>(SparkContext.scala:514)", "spark.jobserver.context.SQLContextFactory$$anon$1.<init>(SQLContextFactory.scala:15)", "spark.jobserver.context.SQLContextFactory.makeContext(SQLContextFactory.scala:15)", "spark.jobserver.context.SQLContextFactory.makeContext(SQLContextFactory.scala:9)", "spark.jobserver.context.SparkContextFactory$class.makeContext(SparkContextFactory.scala:63)", "spark.jobserver.context.SQLContextFactory.makeContext(SQLContextFactory.scala:9)", "spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:135)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)", "spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)", "spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)", "scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)", "spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)", "akka.actor.Actor$class.aroundReceive(Actor.scala:484)", "spark.jobserver.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)", "akka.actor.ActorCell.invoke(ActorCell.scala:495)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)", "akka.dispatch.Mailbox.run(Mailbox.scala:224)", "akka.dispatch.Mailbox.exec(Mailbox.scala:234)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"],
    "causingClass": "java.net.UnknownHostException",
    "message": "java.net.UnknownHostException: namenode"
  }
`

**Comment by velvia** [comment] 2016-12-16 00:40
I don’t think so…

**Comment by barrybecker4** [comment] 2016-12-16 16:40
One other thing I should mention. When I try to build from the top level using
> sbt ++2.11.6 assembly publishLocal
It seems to work fine until it gets to the python project, then it gives the following errors:
`[error] 1 error was encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
/home/barrybecker/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-codec/4.0.37.Final/netty-codec-4.0.37.Final.jar:META-INF/io.netty.versions.properties
/home/barrybecker/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-transport/4.0.37.Final/netty-transport-4.0.37.Final.jar:META-INF/io.netty.versions.properties
/home/barrybecker/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-all/4.0.37.Final/netty-all-4.0.37.Final.jar:META-INF/io.netty.versions.properties
/home/barrybecker/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-buffer/4.0.37.Final/netty-buffer-4.0.37.Final.jar:META-INF/io.netty.versions.properties
/home/barrybecker/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-handler/4.0.37.Final/netty-handler-4.0.37.Final.jar:META-INF/io.netty.versions.properties
/home/barrybecker/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-common/4.0.37.Final/netty-common-4.0.37.Final.jar:META-INF/io.netty.versions.properties
	at sbtassembly.Assembly$.applyStrategies(Assembly.scala:140)
	at sbtassembly.Assembly$.x$1$lzycompute$1(Assembly.scala:25)
	at sbtassembly.Assembly$.x$1$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$lzycompute$1(Assembly.scala:23)
	at sbtassembly.Assembly$.stratMapping$1(Assembly.scala:23)
	at sbtassembly.Assembly$.inputs$lzycompute$1(Assembly.scala:67)
	at sbtassembly.Assembly$.inputs$1(Assembly.scala:57)
	at sbtassembly.Assembly$.apply(Assembly.scala:83)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:240)
	at sbtassembly.Assembly$$anonfun$assemblyTask$1.apply(Assembly.scala:237)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: Building python API received non-zero exit code 1
	at scala.sys.package$.error(package.scala:27)
	at PythonTasks$.buildPythonTask(PythonTasks.scala:22)
	at $1c76c07cea3a69f70dba$$anonfun$jobServerPythonSettings$5.apply(build.sbt:98)
	at $1c76c07cea3a69f70dba$$anonfun$jobServerPythonSettings$5.apply(build.sbt:98)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (root/*:assembly) deduplicate: different file contents found in the following:
[error] /home/barrybecker/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-codec/4.0.37.Final/netty-codec-4.0.37.Final.jar:META-INF/io.netty.versions.properties
`

**Comment by barrybecker4** [comment] 2016-12-16 16:54
Here is the contents of sparkConf that gets passed to SQLContextFactory when creating the sql-context
`spark.akka.threads=12
spark.app.name=sql-context
spark.cores.max=4
spark.driver.allowMultipleContexts=true
spark.driver.extraJavaOptions=-XX:+UseConcMarkSweepGC
         -verbose:gc -XX:+PrintGCTimeStamps -Xloggc:/tmp/job-server/gc.out
         -XX:MaxPermSize=512m
         -XX:+CMSClassUnloadingEnabled  -XX:MaxDirectMemorySize=1G            -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true            -Dcom.sun.management.jmxremote.port=9999            -Dcom.sun.management.jmxremote.rmi.port=9999            -Dcom.sun.management.jmxremote.authenticate=false            -Dcom.sun.management.jmxremote.ssl=false -Dlog4j.configuration=file:/tmp/job-server/log4j-server.properties
              -DLOG_DIR=/var/log/job-server -Dspark.executor.uri=/home/spark/spark-2.0.2.tar.gz 
spark.driver.memory=4G
spark.eventLog.dir=hdfs://namenode:8021/directory
spark.eventLog.enabled=true
spark.executor.extraJavaOptions=-Dlog4j.configuration=file:/tmp/job-server/log4j-server.properties
              -DLOG_DIR=/var/log/job-server
spark.executor.memory=1G
spark.executor.uri=/home/spark/spark-2.0.2.tar.gz
spark.jars=file:/tmp/job-server/spark-job-server.jar
spark.master=local[4]
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.submit.deployMode=client
spark.ui.port=4040`

The spark.evenLog.dir has a reference to "namenode" is this the same namenode that is leading to the "UnknownHostException"?

**Comment by barrybecker4** [comment] 2016-12-16 17:04
That reference to namenode in the spark.eventLog.dir must have been the problem because when I set 
spark.eventLog.enabled = false
now I can upload the sqlContext and not get the error!

**Comment by barrybecker4** [comment] 2016-12-16 19:01
We have cucumber bdd tests that we run to verify that our job-server requests work.
I am seeing some odd behavior using this 2.0 preview version. 
When I make a request, I get back a response that says the job has started and gives a job-id.
However, then when I make a request to get the result (or see if its still running) it sometimes works, but other times I get a 404 response with this info

> response = {
>   "status": "ERROR",
>   "result": "No such job ID 1771ea1c-342c-498e-8e1c-719aba7fdbc6"
> }

**Comment by barrybecker4** [comment] 2016-12-16 20:36
I can almost always avoid getting the 4040 "No such ID" error if I introduce a 1/2 second delay before requesting status (via get) after making a request. There must be some sort of timing issue. I wish I understood akka well enough to debug it. I saw a note that there were some timing failures when running the unit tests. If I do sbt test, then the only failures I see have to do with python. How  can I run just the non-python tests? If I try run_tests.sh, then I see ImportError: 

> No module named pyhocon
> java.lang.RuntimeException: Running python tests received non-zero exit code 1

Any debugging tips would be appreciated.

**Comment by barrybecker4** [comment] 2016-12-16 22:55
I found the problem. Its with JobSqlDAO.
I do not get the 404 errors if I switch back to using JobFileDao instead of JobSqlDAO.
The comment in the local.conf.template file makes me uneasy

 ```
# Note: JobFileDAO is deprecated from v0.7.0 because of issues in
 # production and will be removed in future, now defaults to H2 file.
 jobdao = spark.jobserver.io.JobFileDAO
```

It seems that both JobFileDAO and JobSqlDAO have issues, but from what I have seen so far, the JobFileDAO seems to work better. I will open an issue for the JobSqlDAO issue. What were the "issues in production" referred to in the comment?

**Comment by kapil-malik** [comment] 2017-01-13 12:27
We are also trying to run SJS with spark-2.0.1 on production. I started from spark-2.0-preview branch by @f1yegor . However, on JobSQLDao, facing issues -
1. AskTimeoutException : [Open Issue](https://github.com/spark-jobserver/spark-jobserver/issues/679)
2. No out of the box support for MySQL. Had to add flyway scripts and rebuild it.
3. Random 404 errors : As mentioned by @barrybecker4 [above](https://github.com/spark-jobserver/spark-jobserver/issues/543#issuecomment-267690013)

With JobFileDAO, I am stuck to single context per SJS. So we are currently running 6 separate SJS instances !

Any pointers on where to start about #3 above will be great.

**Comment by barrybecker4** [comment] 2017-01-13 15:58
The JobFileDAO is deprecated and has issues, but still works better for us than JobSqlDAO. I wish there were instructions somewhere for how to use JobSqlDAO with MySql or some other database. I wonder if it is hard to setup and configure. What is the purpose of Job*DAO?

**Comment by derSascha** [comment] 2017-01-13 17:06
@barrybecker4 see #701 for MySQL support and have a look on the added files to see what Job*DAO stores.

**Comment by barrybecker4** [comment] 2017-01-13 17:57
Thanks for the tip @derSascha. So to use JobFileDAO with MySql, I just put that configuration into local.conf. I assume I first need to install MySql on linux with something like `sudo apt-get install mysql-server`. Is any configuration of MySql needed?

**Comment by velvia** [comment] 2017-01-13 18:49
Any MySQL should work, as long as there are JDBC drivers for it.
PostGres also works.  There are SJS users using both.

**Comment by barrybecker4** [comment] 2017-01-16 15:36
@derSascha, I am about to attempt to run job-server with JobSqlDAO and MySql and the contents of your pull request, but I still have a few of questions.
I am going to outline what I think the instructions should be (and update them if they need correcting). If you know of actual official instructions somewhere please let me know. It would be good to incorporate some steps like this into the job-server README (using MySQL as an example db) once we figure out what they should be.

1) Install MySql. Identify the location of the drivers for it.
2) Checkout job-server source from git and incorporate @derSasha 's changes in https://github.com/spark-jobserver/spark-jobserver/pull/701 
3) Add the following to environment.conf. 
Question: What is the difference between environment.conf, application.conf and local.conf? We always just use local.conf. They look very similar. Can I just add this configuration to local.conf instead of environment.conf?
{code}
spark {
  jobserver {
    jobdao = spark.jobserver.io.JobSqlDAO
    sqldao {
      slick-driver = slick.driver.MySQLDriver
      jdbc-driver = com.mysql.jdbc.Driver
      jdbc {
        url = "jdbc:mysql://localhost/spark_job_server?createDatabaseIfNotExist=true"
        user = "spark_job_server"
        password = "spark_job_server"
      }
    }
  }
}
flyway.locations="db/mysql/migration"
{code}
Question: where did the url containing "localhost/spark_job_server" come from? Will it likely be the same for me?
4) Do any changes need to be made to the spark-submit command in server_start.sh as suggested by https://github.com/spark-jobserver/spark-jobserver/issues/372 ? 
5) Rebuild job-server jar
6) Run some jobs and look in the database to see if anything gets written.

**Comment by barrybecker4** [comment] 2017-01-16 17:20
I did all of the above, but I get an error when the server attempts to start. It says
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
:
Caused by: org.flywaydb.core.api.FlywayException: Schema `spark_job_server` contains a failed migration to version 0.7.0 !
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:196)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
	at spark.jobserver.io.JobSqlDAO.init(JobSqlDAO.scala:116)
	at spark.jobserver.io.JobSqlDAO.<init>(JobSqlDAO.scala:105)
```

**Comment by derSascha** [comment] 2017-01-16 19:00
@barrybecker4 
 I am not sure what questions are open from your post, so just some notes:

  1. See the [manual steps](https://github.com/spark-jobserver/spark-jobserver#manual-steps). The `application.conf` defines the defaults, no need to change anything here. Copy the `local.conf.template` to `what-you-like.conf` (i named id `environment.conf`) and `setenv.sh` finds it (see [here](https://github.com/spark-jobserver/spark-jobserver/blob/master/bin/setenv.sh#L17)).
  2. My simple example assumes that you have a user `spark_job_server` with password `spark_job_server` in your MySQL Server.
  3. As you already mention: `url = "jdbc:mysql://localhost/spark_job_server?createDatabaseIfNotExist=true"` means that you use the MySQL server at `localhost` and a DB named `spark_job_server` that gets auto create if it does not exists. Some documentation can be found in the [README](https://github.com/spark-jobserver/spark-jobserver#configuring-spark-jobserver-meta-data-database-backend).
  4. I don't know where the 404 timing error comes from... Would be nice if you find the issue!
  5. We found some timing problems on the result API. [This PR](https://github.com/spark-jobserver/spark-jobserver/pull/648) fixed the timing issue running with `JobFileDAO`. Unfortunately it comes back after switching to `JobSQLDAO` and now we have to wait 1/2 second...
  6. Just to mention: We don't use the spark 2.0 preview or MySQL in production right now.

Would be nice to find the timing issue with `JobSqlDAO`.

**Comment by barrybecker4** [comment] 2017-01-16 19:30
Thanks @derSascha. Some responses
1) OK. I did not realize that the .conf file could be called anything.
2) Got it
3) Got it
4) It's rare. Has anyone else that you know of reported it? I'm currently trying to debug #702 since that is reproducible every time.
5) I have that PR in the branch that I am working on. I merged from master recently.
6) OK

**Comment by noorul** [comment] 2017-02-14 04:05
Now we have a branch which seems to be working https://github.com/spark-jobserver/spark-jobserver/tree/spark-2.0-preview . Closing this issue.

**Closed by noorul** 2017-02-14 04:05 UTC
Labels: question

**Comment by barrybecker4** [comment] 2018-03-23 14:40
Just to follow up on the 404 errors problem:
I am pleased to report that with the latest 0.8.1-SNAPSHOT version, I no longer see the intermittent 404 errors when running our cucumber bdd tests. Whatever the problem was it seems to be fixed now.
