### ISSUE TITLE
Kill Job is not working properly

### ISSUE THREAD

**Issue by MeiSign** [spark-jobserver/spark-jobserver#222] opened 2015-08-25 14:41 UTC
We are running in this setup:
spark-jobserver: 0.5.2
spark-version: 1.3.1
master: yarn-client
scala-version: 2.10.4

When we cancel jobs the jobserver responds immediately with job killed and the jobs endpoint says the job is finished. However when we look on our hadoop admin interface the job is still executing and running. It seems like it is not getting killed properly.

Log Output `curl -XDELETE localhost:8090/jobs/33d3a35c-48e7-4ea4-8b14-64d38ee0dfe5`:

```
[2015-08-25 16:31:57,857] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/9c0de523-Importer] - Added broadcast_1_piece0 in memory on berhad02.rz.is:56652 (size: 2.8 KB, free: 530.0 MB)
[2015-08-25 16:31:58,018] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/9c0de523-Importer] - Added broadcast_0_piece0 in memory on berhad02.rz.is:56652 (size: 37.0 KB, free: 530.0 MB)
[2015-08-25 16:31:58,295] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/9c0de523-Importer] - Added broadcast_1_piece0 in memory on berhad16.rz.is:56320 (size: 2.8 KB, free: 530.0 MB)
[2015-08-25 16:31:58,508] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/9c0de523-Importer] - Added broadcast_0_piece0 in memory on berhad16.rz.is:56320 (size: 37.0 KB, free: 530.0 MB)
[2015-08-25 16:36:53,284] INFO  k.jobserver.JobStatusActor [] [akka://JobServer/user/context-supervisor/9c0de523-Importer/status-actor] - Job 33d3a35c-48e7-4ea4-8b14-64d38ee0dfe5 killed
```

Hadoop Backend after killing the job. I am wondering why the JobId is 0?
![image](https://cloud.githubusercontent.com/assets/3068473/9469545/f51301ae-4b47-11e5-9242-d4142d21be3f.png)

**Comment by velvia** [comment] 2015-08-28 16:39
Stefan,

Hmm, will have to debug this some more.   Basically the job set / cancel is
based on SparkContext.setJobGroup().  Will have to debug that and figure
out why it's not cancelling the job group properly.
Might be an issue in Spark itself we need to fix.

I assume your job does not spin up other threads right?

On Tue, Aug 25, 2015 at 7:41 AM, Stefan Meiwald <notifications@github.com>
wrote:

> We are running in this setup:
> spark-jobserver: 0.5.2
> spark-version: 1.3.1
> master: yarn-client
> scala-version: 2.10.4
>
> When we cancel jobs the jobserver responds immediately with job killed and
> the jobs endpoint says the job is finished. However when we look on our
> hadoop admin interface the job is still executing and running. It seems
> like it is not getting killed properly.
>
> Log Output curl -XDELETE
> localhost:8090/jobs/33d3a35c-48e7-4ea4-8b14-64d38ee0dfe5:
>
> [2015-08-25 16:31:57,857] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/9c0de523-Importer] - Added broadcast_1_piece0 in memory on berhad02.rz.is:56652 (size: 2.8 KB, free: 530.0 MB)
> [2015-08-25 16:31:58,018] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/9c0de523-Importer] - Added broadcast_0_piece0 in memory on berhad02.rz.is:56652 (size: 37.0 KB, free: 530.0 MB)
> [2015-08-25 16:31:58,295] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/9c0de523-Importer] - Added broadcast_1_piece0 in memory on berhad16.rz.is:56320 (size: 2.8 KB, free: 530.0 MB)
> [2015-08-25 16:31:58,508] INFO  k.storage.BlockManagerInfo [] [akka://JobServer/user/context-supervisor/9c0de523-Importer] - Added broadcast_0_piece0 in memory on berhad16.rz.is:56320 (size: 37.0 KB, free: 530.0 MB)
> [2015-08-25 16:36:53,284] INFO  k.jobserver.JobStatusActor [] [akka://JobServer/user/context-supervisor/9c0de523-Importer/status-actor] - Job 33d3a35c-48e7-4ea4-8b14-64d38ee0dfe5 killed
>
> Hadoop Backend after killing the job. I am wondering why the JobId is 0?
> [image: image]
> <https://cloud.githubusercontent.com/assets/3068473/9469545/f51301ae-4b47-11e5-9242-d4142d21be3f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/222>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by MeiSign** [comment] 2015-08-31 15:46
Can't say that for sure because I am not very familar with spark and yarn but I will investigate if it does.

**Comment by zeitos** [comment] 2015-09-25 11:23
This is interesting, cancelling a context with no active job works great for me, never tried cancelling a job.
I'll take a look too.

**Comment by yanlinw** [comment] 2016-03-12 05:29
i experienced the same problem

**Comment by noorul** [comment] 2016-03-16 04:00
We have been using this feature in production for long and never faced such issue. But we are on jobserver 0.6.0

**Comment by barrybecker4** [comment] 2016-04-29 12:27
I have noticed that killing jobs do not stop them right away. My theory is that a message to kill is sent, but it takes a long while to have an effect. If the job is relatively small it will run to completion even though a {code}{"status":"KILLED"}{code} message is returned in response to the DELETE request. 

In our application, we have lots of job requests being sent to the job-server and many times need to cancel ones that were started, but are no longer needed. It would be really great if the jobs would cancel quickly when the DELETE request is sent in order to avoid lots of unnecessary load.

**Comment by velvia** [comment] 2016-04-29 16:53
Hmm.  Is sending a -X DELETE to the context a possible option?  That will definitely kill things.

**Comment by barrybecker4** [comment] 2016-04-29 17:09
I've looked into it more this morning and think I might know what is happening.
It depends on the sort of job that is running. For a job doing group-by and aggregation (only) it seems to be working fine. But for a job that does a simple transformation (like adding a new column based on an expression) followed by an explicit write to disk operation, it has the behavior I saw above. We are writing to a csv file on relatively slow disks. The add column is quick and the write takes 95% of the time. So what I think is happening is that the job cannot be canceled once the write has started. So probably this is expected behavior.

**Comment by velvia** [comment] 2016-04-29 17:15
I think Spark can only cancel future tasks, not the currently executing task.  Thus if a task takes a long time it keeps taking up more resources.  The only way to really *kill* a long running task is by deleting the context, which I believe sends an asynchronous message to the executors to die.

**Comment by v-gerasimov** [comment] 2016-12-19 09:26
Any update on this? Seems I have the same issue, but I run a job on Spark standalone mode without yarn.

**Comment by v-gerasimov** [comment] 2016-12-19 12:23
I figure out the problem. It happens because we run a job in Future and set job group there (see: JobManagerActor.getJobFuture method) but kill the job asynchronously by cancel job group, sometimes before spark job runs.

**Comment by velvia** [comment] 2016-12-20 08:29
Ah, good to hear you figured this out.  Is there any action here or should we close it?

**Comment by barrybecker4** [comment] 2017-01-16 18:39
Probably this issue can be closed. 
I just opened [#702](https://github.com/spark-jobserver/spark-jobserver/issues/702) for unexpected behavior when requesting the result of a canceled job when useing JobSqlDAO.

**Comment by tvvsatish** [comment] 2017-11-26 18:50
It happened in my case as well. I have tested various scenarios long running jobs and short running jobs. According to my findings cancelling job by sparkContext.cancelJobGroup(jobId) cancels only current running or active jobs, but in a spark-job-server job multiple jobs are created, a job of a jobGroup can be created after completion of previous job. so the above method cancels only jobs running at that time but not the later jobs of the same job group. so if cancel job comes in between jobs or your job-server job has a failure handling then spark job still continues in the context but job-server status is marked as error.

**Comment by bsikander** [comment] 2019-05-10 14:56
Closing. For streaming jobs, please delete the context.

**Closed by bsikander** 2019-05-10 14:56 UTC
Labels: bug, yarn
