### ISSUE TITLE
Ask timed out on [Actor[akka://] after [10000 ms]"

### ISSUE THREAD

**Issue by yanghao007** [spark-jobserver/spark-jobserver#898] opened 2017-07-21 05:13 UTC
public class JavaWorkCount implements JSparkJob<List<Tuple2<String, Integer>>> {

    public List<Tuple2<String, Integer>> run(JavaSparkContext sc, JobEnvironment runtime, Config data) {
        String[] works = data.getString("input.string").split(" ");

        JavaRDD<String> wordRDD = sc.parallelize(Arrays.asList(works));
        JavaPairRDD<String, Integer> kvs = wordRDD.mapToPair(new PairFunction<String, String, Integer>() {
            public Tuple2<String, Integer> call(String s) throws Exception {
                return new Tuple2<String, Integer>(s, 1);
            }
        }).reduceByKey(new Function2<Integer, Integer, Integer>() {
            public Integer call(Integer v1, Integer v2) throws Exception {
                return v1 + v2;
            }
        });
        List<Tuple2<String, Integer>> wordCounts = kvs.collect();
        return wordCounts;
    }

    public Config verify(JavaSparkContext sc, JobEnvironment runtime, Config config) {
        return config;
    }
}

what's wrong?

**Comment by velvia** [comment] 2017-07-21 06:06
Hi, can you please respond with basic info:
- Job server version
- Spark and Scala version
- How to reproduce your error

**Comment by yanghao007** [comment] 2017-07-21 06:58
sjs_version: 0.7.0
spark_version: 1.6.3
scala_version: 2.11.8

this is error log:
[2017-07-21 14:05:12,925] ERROR .jobserver.JobManagerActor [] [] - About to restart actor due to exception:
java.lang.ClassCastException: spark.jobserver.JavaHelloWorldJob cannot be cast to spark.jobserver.api.SparkJobBase
	at spark.jobserver.context.ScalaContextFactory$class.loadAndValidateJob(SparkContextFactory.scala:92)
	at spark.jobserver.context.DefaultSparkContextFactory.loadAndValidateJob(SparkContextFactory.scala:114)
	at spark.jobserver.JobManagerActor.startJobInternal(JobManagerActor.scala:241)
	at spark.jobserver.JobManagerActor$$anonfun$wrappedReceive$1.applyOrElse(JobManagerActor.scala:167)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at spark.jobserver.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:25)
	at spark.jobserver.common.akka.Slf4jLogging$class.spark$jobserver$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:34)
	at spark.jobserver.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:24)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
	at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
	at spark.jobserver.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:23)


thanks

**Comment by tristanwietsma** [comment] 2017-07-21 21:06
I'm getting a similar problem when testing via docker with the word count example:

```shell
> docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
sparkjobserver/spark-jobserver   latest              7a188f2d0dff        3 months ago        1.37GB
> docker run -d -p 8090:8090 sparkjobserver/spark-jobserver
```

Submitting the JAR was fine:

```shell
> curl --data-binary @job-server-tests/target/scala-2.11/job-server-tests_2.11-0.8.0-SNAPSHOT.jar 127.0.0.1:8090/jars/test
{
  "status": "SUCCESS",
  "result": "Jar uploaded"
}
```

First attempt to run the job throws an error, but it shows up in the UI:

```
> curl -d "input.string = a b c a b see" "127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample"
{
  "status": "ERROR",
  "result": {
    "message": "Ask timed out on [Actor[akka://JobServer/user/job-info#2037952702]] after [3000 ms]",
    "errorClass": "akka.pattern.AskTimeoutException",
    "stack": ["akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)", "akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)", "scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)", "scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)", "akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)", "akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)", "akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)", "akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)", "java.lang.Thread.run(Thread.java:745)"]
  }
}
```

The job shows up under running, but on closer inspection of the the `(C)` link next to the job, it says there is no such ID:

![screen shot 2017-07-21 at 4 03 44 pm](https://user-images.githubusercontent.com/1371478/28482488-33f25ff4-6e2e-11e7-8767-40165361ab8e.png)

Resubmitting the same job seems to work, but it just hangs (presumably blocked by the previous job). The `(C)` link displays the payload correctly.

```
curl -d "input.string = a b c a b see" "127.0.0.1:8090/jobs?appName=test&classPath=spark.jobserver.WordCountExample" 
{
   "classPath" : "spark.jobserver.WordCountExample",
   "context" : "529aa15c-spark.jobserver.WordCountExample",
   "duration" : "Job not done yet",
   "jobId" : "c9fdf311-c914-4beb-bf70-5d8f57220b08",
   "startTime" : "2017-07-21T20:50:29.524Z",
   "status" : "STARTED"
}
```

![screen shot 2017-07-21 at 4 02 21 pm](https://user-images.githubusercontent.com/1371478/28482466-10860c6e-6e2e-11e7-831e-8cc5baa3b348.png)

When I try to delete the jobs via REST, I get a 500 error with `The server was not able to produce a timely response to your request.`

**Comment by bluestreek18** [comment] 2017-08-07 19:06
I had the same error and it turned out my classPath was set incorrectly.

**Comment by tristanwietsma** [comment] 2017-08-07 19:13
Ah, interesting. I'll check the dockerfile; might be a stale build.

**Comment by kavemun** [comment] 2017-08-26 04:43
I'm having the same issue, is there any update?

@bluestreek18 can you elalaborate about the classPath? thanks.

**Comment by ghukill** [comment] 2017-09-14 13:25
Also having the same issue.  

Pulled docker image 9/14, running like this:
```
docker run -d -p 8090:8090 sparkjobserver/spark-jobserver:0.7.0.mesos-0.25.0.spark-1.6.2 
```
believe my spark-jobserver version is: `0.8.0-SNAPSHOT`

**Comment by cubean** [comment] 2017-10-12 07:25
Got the same issue in velvia/spark-jobserver:0.8.0-SNAPSHOT.mesos-1.0.0.spark-2.2.0.scala-2.11.jdk-8-jdk.

Waiting update...

**Comment by cubean** [comment] 2017-10-13 00:25
I solved this problem. That's not the issue of the job server. Just because I missed a worker node in the spark cluster. I checked the http://<IP Address>:8080 and found it.

Now, the docker (velvia/spark-jobserver:0.8.0-SNAPSHOT.mesos-1.0.0.spark-2.2.0.scala-2.11.jdk-8-jdk) in master branch with spark cluster mode is working.

**Comment by velvia** [comment] 2017-10-13 06:17
Great!   Can we close this

**Comment by linsimiao** [comment] 2018-07-13 09:29
i met with the similar problem, and besides throwing the error, the session context that i tried to run my job with is lost at the same time.  When I tried to new a session context again, the following error was throw.
`{
"status: "CONTEXT_INIT_ERROR",
"result: {
"message" : "Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder' : ',
"errorClass": "java.lang.IllegalArgumentException",
"stack": "java.lang.IllegalArgumentException": Error while instantiating org.apache.spark.sql.hive.HiveSessionStateBuilder'' ...
}
}`

**Comment by bsikander** [comment] 2019-06-07 13:45
Closing. The root cause has been understood. If any other problem occurs then can be tracked in the other ticket.

**Closed by bsikander** 2019-06-07 13:45 UTC
