### ISSUE TITLE
JAR manager AskTimeoutException

### ISSUE THREAD

**Issue by hectcastro** [spark-jobserver/spark-jobserver#381] opened 2016-02-03 19:22 UTC
On startup, we occasionally see this error:

```
2016-02-03 19:12:39,311 [JobServer-akka.actor.default-dispatcher-2] INFO  akka.event.slf4j.Slf4jLogger -  Slf4jLogger started
2016-02-03 19:12:43,262 [main] INFO  spark.jobserver.io.JobSqlDAO -  rootDir is /opt/spark-jobserver/data
2016-02-03 19:12:48,273 [JobServer-akka.actor.default-dispatcher-2] INFO  spark.jobserver.JarManager -  Starting actor spark.jobserver.JarManager
2016-02-03 19:12:48,277 [JobServer-akka.actor.default-dispatcher-3] INFO  spark.jobserver.DataManagerActor -  Starting actor spark.jobserver.DataManagerActor
2016-02-03 19:12:48,666 [JobServer-akka.actor.default-dispatcher-5] INFO  spark.jobserver.LocalContextSupervisorActor -  Starting actor spark.jobserver.LocalContextSupervisorActo
r
2016-02-03 19:12:48,668 [main] INFO  spark.jobserver.JobServer$ -  Adding initial job jars: {
    # spark-jobserver.conf: 15
    "geoprocessing-0.4.0" : "/opt/geoprocessing/mmw-geoprocessing-0.4.0.jar"
}

2016-02-03 19:12:48,669 [JobServer-akka.actor.default-dispatcher-4] INFO  spark.jobserver.JobInfoActor -  Starting actor spark.jobserver.JobInfoActor
2016-02-03 19:12:49,230 [JobServer-akka.actor.default-dispatcher-4] INFO  spark.jobserver.JobResultActor -  Starting actor spark.jobserver.JobResultActor
2016-02-03 19:13:03,690 [main] ERROR spark.jobserver.JobServer$ -  Unable to start Spark JobServer: 
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://JobServer/user/jar-manager#-2104092633]] after [15000 ms]
        at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
        at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:691)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
        at java.lang.Thread.run(Thread.java:745)
```

I'm having a difficult time trying to repeatedly reproduce this error, and when I do, it has been difficult to determine why it happens. Is related to JAR size, or long durations due to larger JARs? If so, is there a mechanism to increase the timeout just for JAR manager operations?

**Comment by velvia** [comment] 2016-02-03 20:29
Hector,

Sorry which version are you using again?  In master, the JarManager is only used in the routes to post a new jar, and not in starting a new job.

-Evan

**Comment by hectcastro** [comment] 2016-02-03 20:35
Sure. Sorry for not including that originally. I'm on 0.6.1.

**Comment by hectcastro** [comment] 2016-02-03 22:17
We are not POSTing a job at all. We are using the `job-jar-paths` setting.

Below is our SJS configuration:

```scala
###################
# spark-jobserver #
###################

spark.jobserver {
  port = 8090
  jobdao = spark.jobserver.io.JobSqlDAO

  sqldao {
    rootdir = /opt/spark-jobserver/data
    jdbc.url = "jdbc:h2:file://opt/spark-jobserver/data/h2-db"
  }

  job-jar-paths {
    "geoprocessing-0.4.0" = /opt/geoprocessing/mmw-geoprocessing-0.4.0.jar
  }
}

spark.contexts {
  geoprocessing {}
}

#########
# spark #
#########

spark {
  home = "/opt/spark"
  master = "local[*]"

  context-settings.passthrough.spark.serializer = "org.apache.spark.serializer.KryoSerializer"
  context-settings.passthrough.spark.kryo.registrator = "geotrellis.spark.io.hadoop.KryoRegistrator"
}

#########
# spray #
#########

spray.can.server.parsing.max-content-length = 250m
```

**Comment by velvia** [comment] 2016-02-04 07:19
So it seems the problem is job server is timing out trying to store those initial jars in the database.  You can try tuning this parameter:

spark.jobserver.context-creation-timeout

which unfortunately also controls the timing of storing those initial jars.  It defaults to 15 seconds, thus your timeout.

Perhaps H2 has a problem storing large jars….

-Evan

**Comment by hectcastro** [comment] 2016-02-04 19:33
Nice. That settings is helping us get past this exception. For the record, our JAR is ~73MB right now.

Would you like me to close this issue, or do you want to keep it open to track H2 and large JARs?

**Comment by velvia** [comment] 2016-02-04 19:36
Go ahead and close it, thanks.  I’ll add your use case to the Troubleshooting section.

**Closed** 2016-02-04 19:38 UTC
