### ISSUE TITLE
Run each context in a different process

### ISSUE THREAD

**Issue by Ankit1010** [spark-jobserver/spark-jobserver#87] opened 2015-03-13 19:23 UTC
Running multiple contexts at once in unstable in Spark 1.2/Jobserver 0.5 as spark does not support multiple contexts in the same JVM (https://issues.apache.org/jira/browse/SPARK-2243). Refactoring the jobserver to launch each context in a different process & JVM would allow running multiple contexts smoothly.

**Comment by petro-rudenko** [comment] 2015-03-13 19:42
+1 for this, but not sure how easily to do this in current jobserver architecture.

**Comment by velvia** [comment] 2015-03-14 18:44
Not trivial, but no major design overhauls are needed.  This was intended from the beginning. 

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by Ankit1010** [comment] 2015-03-18 00:46
I have been taking a look at implementing this based on your comments. This is the general idea i have -

AkkaClusterSupervisor:
  Subscribes to cluster events.
  Maintains a set of ActorRefs pointing to free job manager actors. When a member joins the cluster (MemberUp message), it is added to the set.
JobManagerActors constructor is changed to only take a JobDAO, and the Initialize message takes in the rest - (context name, context config, isAdhoc, resultActor)
  On creating a context, it sends a Initialize message to a free job manager with the context details or errors if there are none available.
  When JobManager finishes a job, it will send some message to supervisor in addition to the status/result actors. This will allow the supervisor to add it back to the set of free job managers.
  I think we will also have to handle the MemberExited and MemberRemoved message from the cluster to manage free job managers.
 
Or perhaps a better approach is to restart the JobManagerActor after a job is complete? I am thinking it would then just rejoin the cluster so there is no need for it to notify supervisor when job is complete.

Would love to hear your thoughts on this.

**Comment by petro-rudenko** [comment] 2015-03-18 13:58
How does the akka cluster would be managed? The user would start on each node separate process or it will be managed by spark akka system (every spark worker would spawn a process)? If the user have to manage akka cluster (start professes manually on all the nodes, monitor if the process died - then restart, etc.) it's not very convinient. The easiest possible workaround is to put jobserver behind load balancer (apache/nginx) and start separate jobserver process on a new port from the pool.

But since jobserver JVM  keeps spark context (driver) it needs to have a lot of memory, for operations like collect, etc.

The ideal solution for yarn I see, is to use yarn-cluster mode (where spark context would leave on application master process, rather then on jobserver process) and kill/monitor jobs through yarn api. But it's just yarn specific workaround.

**Comment by velvia** [comment] 2015-03-19 20:05
@Ankit1010:  hmm..  not quite.

A JobManager(Actor) corresponds to a context.

The ClusterSupervisor would listen for cluster events, as you suggest, and also keep a list of other JobManagerActors, which should have a node type of "jobManager", which are from the cluster events.

The difference is, instead of looking for a "free" manager,  the CLusterSupervisor, like the Local one today, would look up the manager corresponding to the context the job is supposed to run under.  The job would be submitted to that context, just like today.

If a context needs to be created (either explicitly or due to an ad-hoc job), and is not in the list of contexts, then the CLusterSupervisor can launch a new process, which will eventually cause that to be a new node in the cluster.  That can then be a JobManagerActor to send jobs to.

So, really, the logic is pretty similar to the LocalContextSupervisor, except
1) instead of createContext creating the context locally, it has to launch a process and start it remotely
2) use cluster messages to know if another job server ClusterSupervisor (imagine there are two job server processes) has created a jobManager process (in which case it would join the ring).

There would be at least two types of nodes: a jobServer node and a jobManager node.

Testing this can be done using `sbt-multi-jvm` to simulate multiple remote JobManagers and JobServers.

To think about: where do the statusActors and resultActors live?

**Comment by Ankit1010** [comment] 2015-03-30 22:41
@velvia 

Thanks for the clarifications. I'm building this out with a single jobserver model for now, all status and result actors will be on the supervisor side, i assume that all nodes share the same filesystem so that I can pass a JobDAO actor reference around when initializing new job managers.

I'm doing something like this to start job managers from the supervisor:
    import java.io.File
    val seperator = File.separator; //System.getProperty("file.seperator")
    val classpath = System.getProperty("java.class.path")
    val javaHome = System.getProperty("java.home")
    val javaPath = javaHome + seperator + "bin" + seperator + "java"

    import spark.jobserver.JobManager
    logger.info("Launching process: {}", javaPath + "-cp " + classpath)
    val pb = new ProcessBuilder(javaPath, "-cp", classpath, JobManager.getClass.getName)
    val process = pb.start()

However the classpath string is empty in this case, so the new JVM does not see the JobManager class  Any ideas on how we can launch a process with the same class path or work around this?

**Comment by velvia** [comment] 2015-03-31 07:23
Hi Ankit,

Instead of wrapping a JobDAO around an actor, I think it would be much more
efficient to initialize a local instance of JobDAO to each JobManager
process, and initialize it from config.

Status actors are always local to each JobManager, they are not with the
supervisor.

Starting the separate process:  Hmmm.  One possibility is to reuse the
server_start script.  However, this would require an assembly to be built
before hand and make running from SBT harder.  I think this is fine
though;  if you want to launch multiple processes you probably shouldn't do
it from SBT anyhow.

-Evan


On Mon, Mar 30, 2015 at 3:41 PM, Ankit Soni <notifications@github.com>
wrote:

> @velvia <https://github.com/velvia>
>
> Thanks for the clarifications. I'm building this out with a single
> jobserver model for now, all status and result actors will be on the
> supervisor side, i assume that all nodes share the same filesystem so that
> I can pass a JobDAO actor reference around when initializing new job
> managers.
>
> I'm doing something like this to start job managers from the supervisor:
> import java.io.File
> val seperator = File.separator; //System.getProperty("file.seperator")
> val classpath = System.getProperty("java.class.path")
> val javaHome = System.getProperty("java.home")
> val javaPath = javaHome + seperator + "bin" + seperator + "java"
>
> import spark.jobserver.JobManagerlogger.info("Launching process: {}", javaPath + "-cp " + classpath)
> val pb = new ProcessBuilder(javaPath, "-cp", classpath, JobManager.getClass.getName)
> val process = pb.start()
>
> However the classpath string is empty in this case, so the new JVM does
> not see the JobManager class Any ideas on how we can launch a process with
> the same class path or work around this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/87#issuecomment-87862404>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by Ankit1010** [comment] 2015-04-08 23:56
@velvia 

Evan - please let me know if the general idea in the PR makes sense.. The first few commits are for an unrelated change (making job caching configurable) that i wasn't sure how to remove. 

This is still in progress - i have not updated the tests yet and the timeouts seem a little shaky. I ended up using a JobDAOActor anyways since JobDAO has state that goes out of sync otherwise. This also only supports a single jobserver.

**Comment by velvia** [comment] 2015-04-09 07:32
Ankit, awesome!  I'll have a look when I have more cycles.

On Wed, Apr 8, 2015 at 4:56 PM, Ankit Soni <notifications@github.com> wrote:

> @velvia <https://github.com/velvia>
>
> Evan - please let me know if the general idea in the PR makes sense.. The
> first few commits are for an unrelated change (making job caching
> configurable) that i wasn't sure how to remove.
>
> This is still in progress - i have not updated the tests yet and the
> timeouts seem a little shaky. I ended up using a JobDAOActor anyways since
> JobDAO has state that goes out of sync otherwise. This also only supports a
> single jobserver.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/87#issuecomment-91071501>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by aabes** [comment] 2015-08-27 12:44
I'm a bit new to spark, so excuse the naivite. In a past project, I was building a container like environment (think tomcat) where  multiple "apps" needed to load the same classes which relied on static variables, initializes etc.
Our solution there was to create a separate classloader per "app" that had its own copy of the statics [ for the jvm the same class loaded by different classloaders, is actually multiple classes]

My reading of the jobmanager actor source made me think that should work with spark, and allow multiple contexts,  as long as each was created from a class loaded vy different class loaders. ( at the time there was an issue of running out of PermGen space, since classes are never Gc'd).

I'm wondering if in cases where you only need a fixed set of contexts,  launching multiple processes (and the associated overhead) can be avoided?

**Comment by velvia** [comment] 2015-08-27 15:09
@aabes this is actually the current design.  `JobManagerActor` creates a custom classloader and uses that for each separate context.   However working with classloaders is really tricky stuff, and the other issue is that Spark actively discourages people from running multiple contexts in the same JVM.  That said, there are folks trying this.

**Comment by velvia** [comment] 2015-10-07 06:06
Hey guys since there is a PR #120 and it will soon be merged into an official branch, hope u don't mind us closing this.  There is also another ticket about HA....

**Closed by velvia** 2015-10-07 06:06 UTC
