### ISSUE TITLE
Support for submitting python and R based jobs

### ISSUE THREAD

**Issue by kishorez** [spark-jobserver/spark-jobserver#491] opened 2016-06-09 05:51 UTC
Hi 

We have a requirement to deploy Python and R based algorithms in Spark Environment. Currently we are experimenting spark job server we have successfully deployed the java based jobs but I couldn't find references for supporting the python and R based jobs.

Can you share your thoughts on supporting in future releases ?

Thanks
Kishore

**Comment by noorul** [comment] 2016-06-09 06:33
Python is not supported yet.

I have seen R related SJS docker,
https://github.com/landauermax/RScalaTest/blob/master/Dockerfile. May be
you need to check with the author. I am not sure whether he will receive
this update.

**Comment by velvia** [comment] 2016-06-10 00:13
There is an effort to refactor the API to possibly support Python jobs, but I really need to work with someone who understands how the Python support works — anybody?

**Comment by hntd187** [comment] 2016-06-10 14:53
I mean @velvia I know Python, does that help?

**Comment by velvia** [comment] 2016-06-10 18:39
The key questions for me are, how exactly are Python jobs run in Spark?   It seems there is a CPython interpreter, and a bridge to a JVM which knows how to serialize and deserialize.   Basically, how does Python job architecture map well to the SJS architecture.   So any help understanding this would be great.

For example right now with the new API, you can have a PythonJobContextFactory which does not deal with SparkJobBase at all.  It deals with a Python class name, etc. etc., and has some Scala code which can invoke this remote Python process…..

**Comment by noorul** [comment] 2016-06-14 04:25
Marking this as a duplicate of https://github.com/spark-jobserver/spark-jobserver/issues/196 and closing.

**Closed by noorul** 2016-06-14 04:25 UTC
Labels: duplicate
