### ISSUE TITLE
org.h2.jdbc.JdbcSQLException: Out of memory.

### ISSUE THREAD

**Issue by FK7** [spark-jobserver/spark-jobserver#921] opened 2017-09-08 11:57 UTC
Hi Team,

Getting below exception while uploading jar via cURL.

org.h2.jdbc.JdbcSQLException: Out of memory.; SQL statement:
insert into "JARS" ("APP_NAME","UPLOAD_TIME","JAR")  values (?,?,?) [90108-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:167)
        at org.h2.message.DbException.convert(DbException.java:288)
        at org.h2.table.RegularTable.addRow(RegularTable.java:138)
        at org.h2.command.dml.Insert.insertRows(Insert.java:157)
        at org.h2.command.dml.Insert.update(Insert.java:115)
        at org.h2.command.CommandContainer.update(CommandContainer.java:79)
        at org.h2.command.Command.executeUpdate(Command.java:254)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:158)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:144)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$internalInsert$1.apply(JdbcInsertInvokerComponent.scala:183)
        at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker$$anonfun$internalInsert$1.apply(JdbcInsertInvokerComponent.scala:180)
        at scala.slick.jdbc.JdbcBackend$SessionDef$class.withPreparedInsertStatement(JdbcBackend.scala:198)
        at scala.slick.jdbc.JdbcBackend$BaseSession.withPreparedInsertStatement(JdbcBackend.scala:389)
        at scala.slick.driver.JdbcInsertInvokerComponent$ReturningInsertInvoker.preparedInsert(JdbcInsertInvokerComponent.scala:301)
        at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.internalInsert(JdbcInsertInvokerComponent.scala:180)
        at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.insert(JdbcInsertInvokerComponent.scala:175)
        at scala.slick.driver.JdbcInsertInvokerComponent$InsertInvokerDef$class.$plus$eq(JdbcInsertInvokerComponent.scala:70)
        at scala.slick.driver.JdbcInsertInvokerComponent$BaseInsertInvoker.$plus$eq(JdbcInsertInvokerComponent.scala:145)
        at spark.jobserver.io.JobSqlDAO$$anonfun$insertJarInfo$1.apply(JobSqlDAO.scala:140)
        at spark.jobserver.io.JobSqlDAO$$anonfun$insertJarInfo$1.apply(JobSqlDAO.scala:138)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$3.withSession(JdbcBackend.scala:46)
        at spark.jobserver.io.JobSqlDAO.insertJarInfo(JobSqlDAO.scala:137)
        at spark.jobserver.io.JobSqlDAO.saveJar(JobSqlDAO.scala:111)
        at spark.jobserver.io.JobDAOActor$$anonfun$wrappedReceive$1.applyOrElse(JobDAOActor.scala:45)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)
        at ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)
        at ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.OutOfMemoryError: Requested memory: 322481556
        at org.h2.mvstore.DataUtils.newBytes(DataUtils.java:833)
        at org.h2.store.Data.expand(Data.java:1296)
        at org.h2.store.Data.checkCapacity(Data.java:1291)
        at org.h2.store.PageLog.logAddOrRemoveRow(PageLog.java:653)
        at org.h2.store.PageStore.logAddOrRemoveRow(PageStore.java:1464)
        at org.h2.index.PageDataIndex.addTry(PageDataIndex.java:208)
        at org.h2.index.PageDataIndex.add(PageDataIndex.java:137)
        at org.h2.table.RegularTable.addRow(RegularTable.java:120)
        ... 47 more
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by thoHeinze** [comment] 2017-09-09 11:09
@FK7: Which version of the Spark Jobserver are you using?

**Comment by FK7** [comment] 2017-09-11 07:21
@thoHeinze: I am using below branch. 
https://github.com/bjoernlohrmann/spark-jobserver/tree/0.6.2-KNIME_cdh-5.8

**Comment by thoHeinze** [comment] 2017-09-11 07:26
@FK7  Ok, the Spark Jobserver had a problem with this version, that all jars were stored very inefficiently inside the H2 database. This was fixed by the PR https://github.com/spark-jobserver/spark-jobserver/pull/881. I think you have now a few options: 1) use the current master, 2) switch to FileDAO in Spark Jobserver 3) significantly reduce the number of Jars you store inside the jobserver.

**Comment by FK7** [comment] 2017-09-11 10:30
@thoHeinze Thanks for giving me options. Appreciate your help !!!

**Comment by derSascha** [comment] 2017-09-11 18:53
@FK7 What size has your jar file?

    Caused by: java.lang.OutOfMemoryError: Requested memory: 322481556

This sounds like a huge file. Try to put the jars on your server and upload only a small jar via the API (containing the jobs only).

**Comment by FK7** [comment] 2017-09-14 13:40
@thoHeinze Option 2 worked for me, Thanks for your help.

**Closed** 2017-09-14 13:40 UTC
