### ISSUE TITLE
HA Failover for Job Server

### ISSUE THREAD

**Issue by phil-monroe** [spark-jobserver/spark-jobserver#42] opened 2015-01-09 04:09 UTC
From what I can tell, the JobDAO's are for keeping the important mutable state. If a DAO was implemented to keep configs in Redis or PostgreSQL, would the job server be stateless enough to properly work with multiple instances of the jobserver backed by a central DB?

If so, then I could POST a jar to one instance and run the app from a separate instance. Correct?

I've noticed that the SQL DAO can take JDBC configuration in the ooyala repo, which seems promising.

**Comment by velvia** [comment] 2015-01-09 08:23
Hi Phil,

Which configs are you talking about?  Job configs are already persisted via
the DAO.

Multiple instances of jobserver can work as you describe and function off
of a central DB, but they will not be aware of the contexts that the other
jobservers have, and syncing the status between servers doesn't work
completely.

POSTing a jar to one instance and running the app from the other should
work in theory, but there may be bugs.

Basically, more testing is needed, and a real syncing mechanism between
multiple instances would be much better.   I haven't had a chance to
revisit the DAO.

On Thu, Jan 8, 2015 at 8:09 PM, Phil Monroe <notifications@github.com>
wrote:

> From what I can tell, the JobDAO's are for keeping the important mutable
> state. If a DAO was implemented to keep configs in Redis or PostgreSQL,
> would the job server be stateless enough to properly work with multiple
> instances of the jobserver backed by a central DB?
>
> If so, then I could POST a jar to one instance and run the app from a
> separate instance. Correct?
>
> I've noticed that the SQL DAO can take JDBC configuration in the ooyala
> repo, which seems promising.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/42>.
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by phil-monroe** [comment] 2015-01-09 20:26
@velvia,

Thanks for the quick response. Here is my dream for a job scheduling/execution service:

![img_0473](https://cloud.githubusercontent.com/assets/723421/5686435/906f51f2-97f7-11e4-8647-52a5b7f5e163.JPG)

In this scenario, we would have some sort to time based CRON like service that kicks off jobs at regular intervals and a realtime service that kicks off jobs every time something important happens (new users signs up, a different job is finishes and triggers another job, etc...). If we had this kind of a setup, if a jobserver node goes down, there are others that can handle the need for running jobs in a high availability kind of way. Finally, all the job deployment scripts would need to do is POST new jars at the loadbalancer and all new jobs started will use the updated job regardless of which node it starts on. 

Overall, this will probably lead to a feature request, with me and my team actually contributing to the implementation. Just wanted to get some thoughts from the core contributors before charging down that route.

**Comment by phil-monroe** [comment] 2015-01-09 20:30
Regarding contexts: something would need to be persisted to the central DB to store the configs related to a spark context (num cpus / memory requirements / whatever). When a job is started with a specific context, if the context is not already initialized in a jobserver node, it would have to create one with that configuration.

**Comment by velvia** [comment] 2015-01-10 08:37
Hmm...  ok so let's say that on node 1 I create a context Foo, and this
gets persisted to the database.
Someone then wants to run a job on context Foo but sends this to node 2,
which does not have said context Foo.  It sees it in the database, so then
it starts context Foo on node 2.

Is this what we want?

I would have thought that the better behavior is for node 2 to be aware of
node 1, and to route the request to start the job on Foo to node 1 which
already has foo.

However, if node 1 dies, then node 2 can pick up where node 1 left off,
hopefully....

I'll have a look at your other email soon, but overall I don't believe the
database is a good communication or messaging medium.  In fact, the job
server was designed for different nodes to talk to each other using Akka
messaging, with the DB only persisting.

On Fri, Jan 9, 2015 at 12:30 PM, Phil Monroe <notifications@github.com>
wrote:

> Regarding contexts: something would need to be persisted to the central DB
> to store the configs related to a spark context (num cpus / memory
> requirements / whatever). When a job is started with a specific context, if
> the context is not already initialized in a jobserver node, it would have
> to create one with that configuration.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/42#issuecomment-69394126>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by velvia** [comment] 2015-01-13 09:24
Anyways, let's discuss in more detail.  I think this is a highly requested
feature and having HA would be very valuable.  Just have to define exactly
what HA means.

On Sat, Jan 10, 2015 at 12:37 AM, Evan Chan <velvia@gmail.com> wrote:

> Hmm...  ok so let's say that on node 1 I create a context Foo, and this
> gets persisted to the database.
> Someone then wants to run a job on context Foo but sends this to node 2,
> which does not have said context Foo.  It sees it in the database, so then
> it starts context Foo on node 2.
>
> Is this what we want?
>
> I would have thought that the better behavior is for node 2 to be aware of
> node 1, and to route the request to start the job on Foo to node 1 which
> already has foo.
>
> However, if node 1 dies, then node 2 can pick up where node 1 left off,
> hopefully....
>
> I'll have a look at your other email soon, but overall I don't believe the
> database is a good communication or messaging medium.  In fact, the job
> server was designed for different nodes to talk to each other using Akka
> messaging, with the DB only persisting.
>
> On Fri, Jan 9, 2015 at 12:30 PM, Phil Monroe <notifications@github.com>
> wrote:
>
>> Regarding contexts: something would need to be persisted to the central
>> DB to store the configs related to a spark context (num cpus / memory
>> requirements / whatever). When a job is started with a specific context, if
>> the context is not already initialized in a jobserver node, it would have
>> to create one with that configuration.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/spark-jobserver/spark-jobserver/issues/42#issuecomment-69394126>
>> .
>>
>
>
>
> --
> The fruit of silence is prayer;
> the fruit of prayer is faith;
> the fruit of faith is love;
> the fruit of love is service;
> the fruit of service is peace.  -- Mother Teresa
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by phil-monroe** [comment] 2015-01-13 18:43
Yeah I don't think messaging should go through the DB and akka would be the right solution for that. However, I'm not 100% connivenced that the jobserver nodes will need to communicate with each other at all. Is there a penalty for both node1 and node2 having a context created that is named Foo?

Overall, I would like to see the jobserver nodes being as dumb as possible to keep the complexity low.

**Comment by velvia** [comment] 2015-01-14 08:55
The penalty is that you would have to do client-side sharding.  IE, your
clients have to remember you sent a request to context foo on node 1, and
if there is some state, it has to remember to send to node 1 again.   Foo
on node 1 is a different context than Foo on node 2.  Also, if we end up
implementing HA for contexts, then its difficult for node 1 to know
contexts died on node 2 without communication.

On Tue, Jan 13, 2015 at 10:43 AM, Phil Monroe <notifications@github.com>
wrote:

> Yeah I don't think messaging should go through the DB and akka would be
> the right solution for that. However, I'm not 100% connivenced that the
> jobserver nodes will need to communicate with each other at all. Is there a
> penalty for both node1 and node2 having a context created that is named Foo?
>
> Overall, I would like to see the jobserver nodes being as dumb as possible
> to keep the complexity low.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/42#issuecomment-69795732>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by phil-monroe** [comment] 2015-01-14 23:01
At first I didn't think using different "identical" contexts on different nodes would be that big of an issue, but I just realized that this assumption breaks down when considering named RDD sharing between jobs.  So sorry for the confusion.

With that in mind, then whenever a job is started for a given context, then the request should be forwarded to the proper node that contains that context (which I agree should happen over akka).

That being said, assuming JARS, Job Configs and Job Infos can be stored in a central DB for lookup by any node and jobs are forwarded to the proper node if a context is required, then that will cover most anything needed for scaling out a job server cluster (for now). More would be needed for when context failover is implemented.

**Comment by velvia** [comment] 2015-01-15 08:59
Yeah, I think this sounds about right. 

Notice why there is a class named LocalContextSupervisor.  This is because I imagined there might be a ClusterContextSupervisor. :)

-Evan
"Never doubt that a small group of thoughtful, committed citizens can change the world" - M. Mead

**Comment by qiaohaijun** [comment] 2015-01-19 08:17
what about hdfs ha architure fit HA needs?

**Comment by velvia** [comment] 2015-01-19 08:48
Hi Qiao,

HDFS can be used for checkpointing the state of the context, then it can be
easily recovered on another job server node.   It's not going to replace a
database though as a place of storing / updating config (unless you are
thinking of using HBase), nor will it give you live routing of requests to
contexts.

On Mon, Jan 19, 2015 at 12:17 AM, qiaohaijun <notifications@github.com>
wrote:

> what about hdfs ha architure fit HA needs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/42#issuecomment-70458646>
> .
>



-- 
The fruit of silence is prayer;
the fruit of prayer is faith;
the fruit of faith is love;
the fruit of love is service;
the fruit of service is peace.  -- Mother Teresa

**Comment by velvia** [comment] 2015-09-02 15:27
Let's keep this as the thread for HA design for job server.

1. Base changes on PR #120 
2. Use Akka Cluster to share real-time info on contexts, backed by DB (eg save new contexts as a stream of event updates)
3. Consider what it takes to restart contexts that were running when SJS dies
4. Look into Akka Data Replication library, CRDTs for eventually consistent distributed data that survives network partitions

**Comment by drdwo** [comment] 2016-05-24 14:20
Is there a timeline planned for a syncing mechanism between multiple instances?
>POSTing a jar to one instance and running the app from the other should
>work in theory, but there may be bugs.
Has anyone tried this yet?
Makes load balancing any sense without the syncing mechanism between multiple instances 
(if all jars are available from all instances) or do we definitely need to know on which instance a named context exists to route the call? Are there alternatives to the Akka Cluster solution?

**Comment by velvia** [comment] 2016-05-24 16:55
If all you need is JAR syncing, and you are using a standard shared database (like MySQL or PostGres), then it should work today.

For more advanced syncing like contexts and so forth, that is vaguely on timeline but no specific date.

**Comment by drdwo** [comment] 2016-05-25 09:11
What do you think about a simplified solution for contexts: A controller maintaining a named context -> spark job server node mapping to route context bound job server calls to the node maintaining the named context - without synchronisation. Failover wouldn't work, but if your main goal is to distribute load to different job server instances, is this a valid option?

**Comment by velvia** [comment] 2016-05-26 05:10
Yeah, that would definitely work if all you want is load balancing.  Actually, I’m sure somebody here has deployed such a solution to prod.

**Comment by drdwo** [comment] 2016-05-31 10:07
Regarding jar sharing https://github.com/spark-jobserver/spark-jobserver/issues/127 is still open. Are the plans to fix hdfs jar sharing between spark job server nodes soon?

**Comment by velvia** [comment] 2016-06-01 06:31
There is sort of a workaround - since spark observer is launched with spark-submit now, and you can pass —jars with hdfs paths to load dependencies.  Now we just need a dummy application jar which references the HDFS jars.

**Comment by Nibooor** [comment] 2019-07-24 14:30
Opened this issue https://github.com/spark-jobserver/spark-jobserver/issues/1236 as a specific proposal for HA failover.

**Comment by Nibooor** [comment] 2020-11-06 08:12
Jobserver is effectively HA now.
A documentation on how to set up / use HA can be obtained [here](https://github.com/spark-jobserver/spark-jobserver/blob/master/doc/HA.md).

As there is no work ongoing into that direction, should we close this issue? 
Or does someone want to add something to the topic?

**Closed** 2020-11-16 08:31 UTC
Labels: architecture, enhancement
