### ISSUE TITLE
Job failing after setting context-per-jvm as true in application.conf

### ISSUE THREAD

**Issue by deeptiantony** [spark-jobserver/spark-jobserver#568] opened 2016-08-17 07:54 UTC
Trying to run spark jobs in parallel.After setting context-per-jvm as true in job-server/src/main/resources/application.conf, getting RunTimeException, while attempting curl command for wordcount. If I set it as false,  it works fine.

EXCEPTION:
{
  "status": "ERROR",
  "result": {
    "errorClass": "java.lang.RuntimeException",
    "cause": "Cannot run program \"./manager_start.sh\": error=2, No such file or directory",
    "stack": ["java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)", "scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:68)", "spark.jobserver.AkkaClusterSupervisorActor$$anonfun$1.apply$mcV$sp(AkkaClusterSupervisorActor.scala:221)", "spark.jobserver.AkkaClusterSupervisorActor$$anonfun$1.apply(AkkaClusterSupervisorActor.scala:220)", "spark.jobserver.AkkaClusterSupervisorActor$$anonfun$1.apply(AkkaClusterSupervisorActor.scala:220)", "scala.util.Try$.apply(Try.scala:161)", "spark.jobserver.AkkaClusterSupervisorActor.spark$jobserver$AkkaClusterSupervisorActor$$startContext(AkkaClusterSupervisorActor.scala:220)", "spark.jobserver.AkkaClusterSupervisorActor$$anonfun$wrappedReceive$1.applyOrElse(AkkaClusterSupervisorActor.scala:135)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorStack$$anonfun$receive$1.applyOrElse(ActorStack.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp(Slf4jLogging.scala:26)", "ooyala.common.akka.Slf4jLogging$class.ooyala$common$akka$Slf4jLogging$$withAkkaSourceLogging(Slf4jLogging.scala:35)", "ooyala.common.akka.Slf4jLogging$$anonfun$receive$1.applyOrElse(Slf4jLogging.scala:25)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)", "scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)", "ooyala.common.akka.ActorMetrics$$anonfun$receive$1.applyOrElse(ActorMetrics.scala:24)", "akka.actor.Actor$class.aroundReceive(Actor.scala:467)", "ooyala.common.akka.InstrumentedActor.aroundReceive(InstrumentedActor.scala:8)", "akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)", "akka.actor.ActorCell.invoke(ActorCell.scala:487)", "akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)", "akka.dispatch.Mailbox.run(Mailbox.scala:220)", "akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)", "scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)", "scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)", "scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)", "scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"],
    "causingClass": "java.io.IOException",
    "message": "java.io.IOException: Cannot run program \"./manager_start.sh\": error=2, No such file or directory"
  }

**Comment by noorul** [comment] 2016-08-17 08:21
@deeptiantony How are you deploying SJS?

**Comment by deeptiantony** [comment] 2016-08-17 08:41
@noorul  I started the job server through sbt as job-server/reStart

**Comment by noorul** [comment] 2016-08-17 08:55
Getting multi-jvm to work using reStart is tough. It is not straight forward. I would advice you to do that. Instead follow the actual deployment steps.

**Comment by deeptiantony** [comment] 2016-08-17 09:23
I tried deployment steps using server_deploy.sh. But when I start via server_start.sh, it gets stopped as in PID for corresponding spark-submit close. I get "empty reply from server" message upon using curl command.

**Comment by noorul** [comment] 2016-08-17 09:43
@deeptiantony Can you close this issue as this is not a bug? May be we should use gitter to discuss your particular deployment issue.

**Closed** 2016-08-17 10:21 UTC
