### ISSUE TITLE
Job remains in "RUNNING" status after deleting context

### ISSUE THREAD

**Issue by PierreVincent** [spark-jobserver/spark-jobserver#109] opened 2015-04-01 09:59 UTC
Hi,

I'm currently testing out the Job Server 0.5.1 (compiled from master) against Spark 1.3.0 and things seem to run pretty smoothly so far.

However, I've noticed that when deleting a context that has a job running it, the job remains with a status of "RUNNING".

I have seen this happening for both ad-hoc contexts (created at job submission time) and custom context (create context first, then pass in context when creating the job).

I have also seen this happening for different types of jobs (batch job stopped half-way through and streaming job).

Checking the Spark UI directly shows that the context (application) is correctly completed so I'm guessing this is a problem on the Job Server side that fails to mark the Job as complete (or cancelled/failed, whichever makes sense) when its context is being stopped?

Am I doing something wrong or could this be a bug in the Job Server?

Thanks!

**Comment by velvia** [comment] 2015-04-09 08:07
Hi Pierre,

Hmm....  I think the status should update as "Deleted", but this could be a
bug....

On Wed, Apr 1, 2015 at 2:59 AM, Pierre Vincent <notifications@github.com>
wrote:

> Hi,
>
> I'm currently testing out the Job Server 0.5.1 (compiled from master)
> against Spark 1.3.0 and things seem to run pretty smoothly so far.
>
> However, I've noticed that when deleting a context that has a job running
> it, the job remains with a status of "RUNNING".
>
> I have seen this happening for both ad-hoc contexts (created at job
> submission time) and custom context (create context first, then pass in
> context when creating the job).
>
> I have also seen this happening for different types of jobs (batch job
> stopped half-way through and streaming job).
>
> Checking the Spark UI directly shows that the context (application) is
> correctly completed so I'm guessing this is a problem on the Job Server
> side that fails to mark the Job as complete (or cancelled/failed, whichever
> makes sense) when its context is being stopped?
>
> Am I doing something wrong or could this be a bug in the Job Server?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/109>.
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by cacti77** [comment] 2015-08-12 12:36
I see this too on Job Server 0.5.2 running against Spark 1.3.1. Also, if you try to delete the job that should have been killed when its containing context was deleted, you get "The server was not able to produce a timely response to your request."

**Comment by velvia** [comment] 2015-08-12 15:50
@PierreVincent @cacti77 we should try to reproduce this.  Any thoughts on the job that would take to repro it?

**Comment by cacti77** [comment] 2015-08-13 13:11
@velvia: Sure. This reproduces the problem for me. (Apologies for the code - it was one of the first Scala apps I wrote at the time!)
build.sbt:

    lazy val root = (project in file(".")).
      settings(
        name := "stream_network_wordcount",
        version := "1.0",
        scalaVersion := "2.10.4",
        resolvers += "Job Server Bintray" at "https://dl.bintray.com/spark-jobserver/maven",
        libraryDependencies ++= Seq(
           "spark.jobserver" %% "job-server-api" % "0.5.1" % "provided",
           "org.apache.spark" %% "spark-core" % "1.3.1",
           "org.apache.spark" %% "spark-streaming" % "1.3.1"
        )
      )

StreamNetworkWordCountJob.scala:

    package test
    
    import com.typesafe.config.{Config, ConfigFactory}
    import org.apache.spark._
    import org.apache.spark.streaming._
    import org.apache.spark.storage._
    import spark.jobserver._
    import scala.util.Try

    /**
     * Counts words read in from a network stream. This is based on the Spark
     * example given at https://spark.apache.org/docs/latest/streaming-programming-guide.html#a-quick-example.
     */
    object StreamNetworkWordCountJob extends SparkJob {

      override def validate(sc: SparkContext, config: Config): SparkJobValidation = {
        Try(config.getString("host_name"))
          .map(x => SparkJobValid)
          .getOrElse(SparkJobInvalid("Missing host_name configuration parameter!"))
        // TODO Validate "port" and "batch_interval" as well! I wish I knew scala!
      }

      override def runJob(sc: SparkContext, config: Config): Any = {
        // Debugging (look in Spark Job Server's console output):
        println("host_name = " + config.getString("host_name"))
        println("port  = " + config.getInt("port"))
        println("batch_interval  = " + config.getInt("batch_interval"))

        // Create a Spark Streaming Context from the existing Spark Context.
        // Give it a batch size of batch_interval seconds:
        val ssc = new StreamingContext(sc, Seconds(config.getInt("batch_interval")))

        val lines = ssc.socketTextStream(config.getString("host_name"),
                     config.getInt("port"), StorageLevel.MEMORY_AND_DISK_SER)
        
        val words = lines.flatMap(_.split(" "))
        val wordCounts = words.map(x => (x, 1)).reduceByKey(_ + _)
        wordCounts.print()

        ssc.start()
        ssc.awaitTermination()
      }
    }

post_data.txt:

    host_name=localhost
    port=9998
    batch_interval=5

Build the code with `sbt package`. Upload the resulting jar to a local job-server instance with:

    curl --data-binary @target/scala-2.10/stream_network_wordcount_2.10-1.0.jar localhost:8090/jars/stream_network_wordcount

In a separate terminal start netcat running on localhost:9998:

    nc -lk 9998

Start the streaming app:

    curl --data-binary @post_data.txt "localhost:8090/jobs?appName=stream_network_wordcount&classPath=test.StreamNetworkWordCountJob"

Then kill the context with:

    curl -X DELETE localhost:8090/contexts/<CONTEXT_ID>

The context will die but the job that was started within it will live on with status "RUNNING"! If you don't restart Job Server and keep starting and killing streaming contexts like this then your 'Running Jobs' tab at http://localhost:8090/ clutters up with loads of these zombie jobs after a while. This makes it hard to distinguish the 'real' running jobs from the zombie ones.

**Comment by cacti77** [comment] 2015-08-13 13:15
@velvia: In case it helps, this is what I see in Job Server's stdout at the moment I kill the context:

    Exception in thread "Thread-26" org.apache.spark.SparkException: Job cancelled because SparkContext was shut down
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:699)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:698)
        at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
        at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:698)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:1411)
        at org.apache.spark.util.EventLoop.stop(EventLoop.scala:84)
        at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:1346)
        at org.apache.spark.SparkContext.stop(SparkContext.scala:1380)
        at spark.jobserver.JobManagerActor$$anonfun$postStop$1.apply(JobManagerActor.scala:96)
        at spark.jobserver.JobManagerActor$$anonfun$postStop$1.apply(JobManagerActor.scala:96)
        at scala.Option.foreach(Option.scala:236)
        at spark.jobserver.JobManagerActor.postStop(JobManagerActor.scala:96)
        at akka.actor.Actor$class.aroundPostStop(Actor.scala:475)
        at ooyala.common.akka.InstrumentedActor.aroundPostStop(InstrumentedActor.scala:8)
        at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
        at akka.actor.dungeon.FaultHandling$class.handleChildTerminated(FaultHandling.scala:292)
        at akka.actor.ActorCell.handleChildTerminated(ActorCell.scala:369)
        at akka.actor.dungeon.DeathWatch$class.watchedActorTerminated(DeathWatch.scala:63)
        at akka.actor.ActorCell.watchedActorTerminated(ActorCell.scala:369)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:455)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by velvia** [comment] 2015-08-24 05:57
@cacti thanks, I think this may be a real issue to be fixed, will look into
it.

On Thu, Aug 13, 2015 at 6:15 AM, cacti77 <notifications@github.com> wrote:

> @velvia <https://github.com/velvia>: In case it helps, this is what I see
> in Job Server's stdout at the moment I kill the context:
>
> Exception in thread "Thread-26" org.apache.spark.SparkException: Job cancelled because SparkContext was shut down
>     at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:699)
>     at org.apache.spark.scheduler.DAGScheduler$$anonfun$cleanUpAfterSchedulerStop$1.apply(DAGScheduler.scala:698)
>     at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
>     at org.apache.spark.scheduler.DAGScheduler.cleanUpAfterSchedulerStop(DAGScheduler.scala:698)
>     at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onStop(DAGScheduler.scala:1411)
>     at org.apache.spark.util.EventLoop.stop(EventLoop.scala:84)
>     at org.apache.spark.scheduler.DAGScheduler.stop(DAGScheduler.scala:1346)
>     at org.apache.spark.SparkContext.stop(SparkContext.scala:1380)
>     at spark.jobserver.JobManagerActor$$anonfun$postStop$1.apply(JobManagerActor.scala:96)
>     at spark.jobserver.JobManagerActor$$anonfun$postStop$1.apply(JobManagerActor.scala:96)
>     at scala.Option.foreach(Option.scala:236)
>     at spark.jobserver.JobManagerActor.postStop(JobManagerActor.scala:96)
>     at akka.actor.Actor$class.aroundPostStop(Actor.scala:475)
>     at ooyala.common.akka.InstrumentedActor.aroundPostStop(InstrumentedActor.scala:8)
>     at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
>     at akka.actor.dungeon.FaultHandling$class.handleChildTerminated(FaultHandling.scala:292)
>     at akka.actor.ActorCell.handleChildTerminated(ActorCell.scala:369)
>     at akka.actor.dungeon.DeathWatch$class.watchedActorTerminated(DeathWatch.scala:63)
>     at akka.actor.ActorCell.watchedActorTerminated(ActorCell.scala:369)
>     at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:455)
>     at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
>     at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
>     at akka.dispatch.Mailbox.run(Mailbox.scala:219)
>     at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
>     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark-jobserver/spark-jobserver/issues/109#issuecomment-130664925>
> .
>



-- 
If you are free, you need to free somebody else.
If you have some power, then your job is to empower somebody else.
   --- Toni Morrison

**Comment by mariussoutier** [comment] 2016-06-28 15:03
I have a similar issue with a streaming job. The job itself is in status FINISHED, however the actual Spark job keeps running. Also, the context (ad-hoc) is still active and cannot be deleted.

**Comment by 13h3r** [comment] 2016-07-07 05:04
Any ideas when this can be fixed?

**Comment by mbuccini** [comment] 2016-09-07 13:46
I have an issue similar to the one reported by @mariussoutier. However, in my case, the Streaming job is reported as Failed due to an unhandled exception, while still running and working fine, besides the exception happening occasionally.

**Comment by bsikander** [comment] 2019-05-01 11:13
This has been fixed. Closing it.

**Closed by bsikander** 2019-05-01 11:13 UTC
Labels: bug
